### ISSUE TITLE
how config or set the charset

### ISSUE THREAD

**Issue by hktalent** [billchurch/WebSSH2#10]
[root@appserver ~]# df -h
ÎÄ¼þÏµÍ³              ÈÝÁ¿  ÒÑÓÃ  ¿ÉÓÃ ÒÑÓÃ%% ¹ÒÔØµã
/dev/mapper/VolGroup-lv_root
                      507G  153G  328G  32% /
tmpfs                  16G  1.2M   16G   1% /dev/shm
/dev/xvda1            485M   52M  408M  12% /boot
192.168.10.123:/MyWork
                      985G  223G  712G  24% /MyWork

the “¹ÒÔØµã” cannot display，is china word

**Comment by Mikej81** [comment]
Well, there's you're problem, the code isn't supported in Chinese word.

**Comment by billchurch** [comment]
I accept pull requests, the code is there, the modules I'm using are published (it's probably either needing to pass an environment variable via [ssh2.](https://github.com/mscdex/ssh2) or a setting for [xterm](http://xtermjs.org). I don't have experience working with other character sets so I'm not really the right one for that job.
