### ISSUE TITLE
webssh2 not working with nginx proxy

### ISSUE THREAD

**Issue by piyush94** [billchurch/WebSSH2#107]
**nginx.conf**

```
events {
        worker_connections 1024;
}

http {
        upstream sshserver {
                server localhost:2222;
        }
        server {
                listen 443 ssl;
                server_name a.a.com

                ssl_certificate cer;
                ssl_certificate_key key;

                client_max_body_size 2G;

                proxy_connect_timeout       60000;
                proxy_send_timeout          60000;
                proxy_read_timeout          60000;
                send_timeout                60000;

                location /ssh/ {
                        proxy_pass http://sshserver/ssh/;
                }
        }
}

```

**Comment by piyush94** [comment]
![image](https://user-images.githubusercontent.com/11614204/46210364-25922400-c34e-11e8-95d3-78606f81b136.png)

**Comment by billchurch** [comment]
Take a closer look at your config and your 404 and see the location it’s coming for /ssh isn’t enough.

**Comment by Mikej81** [comment]
I dont know what I am looking at?

**Comment by piyush94** [comment]
Not sure if this is an issue or a shortcoming how the client works, but i fixed it by changing the href in client.htm and changing the socket.io hostname and basepath in index.js

**Comment by vissieGP** [comment]
Hi. 

I have the exact same error. I was able to edit my client.htm file and I can see that worked. 
I do not know what/where to change index.js. I guess that its the index.js in ./client/src, but not sure. Also, it was sort of obvious what to change client.htm too. Its not so obvious for me what to change in index.js.

I believe I am close, help with this will be really appreciated...

Vissie

**Comment by piyush94** [comment]
@vissieGP what i cahnged in index.js inside 'client/src/js/' was following:

->line 49
`if (document.location.pathname) {
  var parts = document.location.pathname.split('/')
  var base = parts.slice(0, parts.length - 1).join('/') + '/'
  var resource = '/**<your nginx proxy path>**/' + 'socket.io'
  console.log(resource);
  socket = io.connect('**<your url e.g. http://abc.com/**', {
    path: resource
  })
  console.log('here');
} else {
  socket = io.connect()
  console.log('not here');
}`

After doing this i remember rebuilding some project maybe this client one, but don't remember exactly.
Hope this is of help to you.
