### ISSUE TITLE
Black screen with ReverseProxy in Apache2.

### ISSUE THREAD

**Issue by rendsolve** [billchurch/WebSSH2#110]
Hi Bill,

In Apache2 conf:
ProxyPass /console http://10.0.0.1:2222
ProxyPassReverse /console http://10.0.0.1:2222

When trying to connect after auth, I get a black screen.
mysite.com/console/ssh/host/10.0.0.10

I can connect with 10.0.0.1:2222/ssh/host/10.0.0.10 it works fine.

Thanks
Phillip

**Comment by billchurch** [comment]
I can’t really help you with the Apache configuration. But it seems like your web socket connection isn’t getting passed back to WebSSH2 from Apache. 

Open up developer tools on your browser and look at the console messages.

**Comment by rendsolve** [comment]
Hey Bill,
These are the console log errors im getting after inputing auth.

webssh2.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
webssh2.bundle.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
webssh2.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

Thanks

**Comment by billchurch** [comment]
@rendsolve what's the path for those? That should show you what you need to proxypass in addtion to what you have above. 

Specifically, /webssh2.css and /webssh2.bundle.js will need to be proxied and proxypass reversed... or you can just drop those in the root of your apache htdocs instance  or whatever it might be...

**Comment by billchurch** [comment]
closing due to no response

**Comment by hktalent** [comment]
@rendsolve 
Apache Module mod_proxy_wstunnel
https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html

**Comment by bicchi** [comment]
Does anyone have a working Apache configuration with WS tunnel? I have been trying to get this to work but so far keep getting an error in my Apache logs:
`..... AH00128: File does not exist: /var/www/html/console/socket.io/, referer:....
`

I even tried copying the 'socket.io' directory to the docroot and no go but with a different error:
`AH01276: Cannot serve directory /var/www/html/console/socket.io/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive, referer
`
I also tried copying all the directories in "app/node_modules/" and didn't work. 

I have created symlinks to the css and js scripts in my docroot folder as shown here:
```
lrwxrwxrwx 1 root root     28 Aug 25 09:39 client.htm -> app/client/public/client.htm
lrwxrwxrwx 1 root root     29 Aug 25 09:39 favicon.ico -> app/client/public/favicon.ico
lrwxrwxrwx 1 root root     29 Aug 25 09:38 webssh2.css -> app/client/public/webssh2.css
lrwxrwxrwx 1 root root     35 Aug 25 09:38 webssh2.bundle.js -> app/client/public/webssh2.bundle.js

```
The relevant portion of my Apache config. 
```
<Location /console>
        RewriteEngine On
        RewriteCond %{REQUEST_URI}  ^/socket.io         [NC]
        RewriteCond %{QUERY_STRING} transport=websocket [NC]
        RewriteRule /(.*) ws://localhost:2222/$1      [P,L]

        ProxyPass http://localhost:2222
        ProxyPassReverse http://localhost:2222
         
        Require all granted
</Location>
```

With this configuration the bottom menu is showing but when i click on it nothing happens. It is worth mentioning that I am able to access it by going directly to port 2222 but trying to do a URL rewrite with Apache. Any help would be appreciated. 

Thanks,
