### ISSUE TITLE
Can it support pre issued commands when terminal is opened?

### ISSUE THREAD

**Issue by danielcainetelastic** [billchurch/WebSSH2#111]
I am wondering if it supports executing some pre issued commands as soon as terminal is opened. For example: ls , go to some specific folder, or executing some applications.

I know you can always open the terminal and manually enter those commands. But it would be great if it can support executing those commands in advance. One use case is letting user open a debug session and all the related debug configurations are sent and enabled once terminal is open so the user does not need to manually enable debug commands.

**Comment by billchurch** [comment]
See #94 for an example of how to do this
