### ISSUE TITLE
Re-auth doesn't work if incorrect auth was provided initially

### ISSUE THREAD

**Issue by vvalchev** [billchurch/WebSSH2#112]
With WebSSH2 v0.2.5 the re-auth functionality will not work, if initially the user provides incorrect credentials.

In that case, the server will log the authentication failure and send the error to the client. However, the menu items will not be drawn, so the user cannot input new credentials.

There are two ways to fix the problem:
- draw the menu, regardless of the error, but in this case you will have useless 'Start Log' entry.
- automatically request the user another authentication credentials

IMHO the second approach is a better and more user-friendly.

**Comment by woowalker** [comment]
anything new?

**Comment by vvalchev** [comment]
I guess @billchurch is on vacation ;)
I hope, when he's back he would merge the change and release a new version probably?

**Comment by billchurch** [comment]
@vvalchev merged, sorry the opposite of vacation. 👍
