### ISSUE TITLE
npm WARN optional Skipping failed optional dependency /@angular/cli/chokidar/fsevents: npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

### ISSUE THREAD

**Issue by LakatanWilfried** [billchurch/WebSSH2#122]
Node version : v8.10.0
Npm version : 3.5.2
Os : Ubuntu 18.04 LTS

root@*******-SATELLITE-C50-B:/home/*******# npm install -g @angular/cli
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular/cli@7.2.0: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @angular/cli@7.2.0: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (culoadDep:symbol-observable ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular-devkit/schematics@7.2.0: wanted: {"node":">= 8.9.0","npm":"loadDep:symbol-observable ▐ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular-devkit/core@7.2.0: wanted: {"node":">= 8.9.0","npm":">= 5.5loadDep:symbol-observable ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @schematics/update@0.12.0: wanted: {"node":">= 8.9.0","npm":">= 5.5.loadDep:symbol-observable ▄ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @schematics/angular@7.2.0: wanted: {"node":">= 8.9.0","npm":">= 5.5.loadDep:symbol-observable ▌ ╢██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular-devkit/architect@0.12.0: wanted: {"node":">= 8.9.0","npm":"/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
/usr/local/lib
└─┬ @angular/cli@7.2.0 
  ├─┬ @angular-devkit/architect@0.12.0 
  │ └─┬ rxjs@6.3.3 
  │   └── tslib@1.9.3 
  ├─┬ @angular-devkit/core@7.2.0 
  │ ├─┬ ajv@6.6.2 
  │ │ ├── fast-deep-equal@2.0.1 
  │ │ ├── json-schema-traverse@0.4.1 
  │ │ └─┬ uri-js@4.2.2 
  │ │   └── punycode@2.1.1 
  │ ├─┬ chokidar@2.0.4 
  │ │ ├─┬ anymatch@2.0.0 
  │ │ │ └─┬ micromatch@3.1.10 
  │ │ │   ├── arr-diff@4.0.0 
  │ │ │   ├─┬ define-property@2.0.2 
  │ │ │   │ └─┬ is-descriptor@1.0.2 
  │ │ │   │   ├── is-accessor-descriptor@1.0.0 
  │ │ │   │   └── is-data-descriptor@1.0.0 
  │ │ │   ├─┬ extend-shallow@3.0.2 
  │ │ │   │ ├── assign-symbols@1.0.0 
  │ │ │   │ └─┬ is-extendable@1.0.1 
  │ │ │   │   └── is-plain-object@2.0.4 
  │ │ │   ├─┬ extglob@2.0.4 
  │ │ │   │ ├─┬ define-property@1.0.0 
  │ │ │   │ │ └─┬ is-descriptor@1.0.2 
  │ │ │   │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │   │ │   └── is-data-descriptor@1.0.0 
  │ │ │   │ ├─┬ expand-brackets@2.1.4 
  │ │ │   │ │ ├── define-property@0.2.5 
  │ │ │   │ │ ├── extend-shallow@2.0.1 
  │ │ │   │ │ └── posix-character-classes@0.1.1 
  │ │ │   │ └── extend-shallow@2.0.1 
  │ │ │   ├── fragment-cache@0.2.1 
  │ │ │   ├── kind-of@6.0.2 
  │ │ │   ├─┬ nanomatch@1.2.13 
  │ │ │   │ └── is-windows@1.0.2 
  │ │ │   ├── object.pick@1.3.0 
  │ │ │   └── regex-not@1.0.2 
  │ │ ├── async-each@1.0.1 
  │ │ ├─┬ braces@2.3.2 
  │ │ │ ├── arr-flatten@1.1.0 
  │ │ │ ├── array-unique@0.3.2 
  │ │ │ ├─┬ extend-shallow@2.0.1 
  │ │ │ │ └── is-extendable@0.1.1 
  │ │ │ ├─┬ fill-range@4.0.0 
  │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ ├─┬ is-number@3.0.0 
  │ │ │ │ │ └─┬ kind-of@3.2.2 
  │ │ │ │ │   └── is-buffer@1.1.6 
  │ │ │ │ ├── repeat-string@1.6.1 
  │ │ │ │ └── to-regex-range@2.1.1 
  │ │ │ ├── isobject@3.0.1 
  │ │ │ ├── repeat-element@1.1.3 
  │ │ │ ├─┬ snapdragon@0.8.2 
  │ │ │ │ ├─┬ base@0.11.2 
  │ │ │ │ │ ├─┬ cache-base@1.0.1 
  │ │ │ │ │ │ ├─┬ collection-visit@1.0.0 
  │ │ │ │ │ │ │ ├── map-visit@1.0.0 
  │ │ │ │ │ │ │ └── object-visit@1.0.1 
  │ │ │ │ │ │ ├── get-value@2.0.6 
  │ │ │ │ │ │ ├─┬ has-value@1.0.0 
  │ │ │ │ │ │ │ └─┬ has-values@1.0.0 
  │ │ │ │ │ │ │   └── kind-of@4.0.0 
  │ │ │ │ │ │ ├─┬ set-value@2.0.0 
  │ │ │ │ │ │ │ └── extend-shallow@2.0.1 
  │ │ │ │ │ │ ├─┬ to-object-path@0.3.0 
  │ │ │ │ │ │ │ └── kind-of@3.2.2 
  │ │ │ │ │ │ ├─┬ union-value@1.0.0 
  │ │ │ │ │ │ │ └─┬ set-value@0.4.3 
  │ │ │ │ │ │ │   └── extend-shallow@2.0.1 
  │ │ │ │ │ │ └─┬ unset-value@1.0.0 
  │ │ │ │ │ │   └─┬ has-value@0.3.1 
  │ │ │ │ │ │     ├── has-values@0.1.4 
  │ │ │ │ │ │     └── isobject@2.1.0 
  │ │ │ │ │ ├─┬ class-utils@0.3.6 
  │ │ │ │ │ │ ├── arr-union@3.1.0 
  │ │ │ │ │ │ ├── define-property@0.2.5 
  │ │ │ │ │ │ └─┬ static-extend@0.1.2 
  │ │ │ │ │ │   ├── define-property@0.2.5 
  │ │ │ │ │ │   └─┬ object-copy@0.1.0 
  │ │ │ │ │ │     ├── copy-descriptor@0.1.1 
  │ │ │ │ │ │     ├── define-property@0.2.5 
  │ │ │ │ │ │     └── kind-of@3.2.2 
  │ │ │ │ │ ├── component-emitter@1.2.1 
  │ │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ │ ├─┬ mixin-deep@1.3.1 
  │ │ │ │ │ │ ├── for-in@1.0.2 
  │ │ │ │ │ │ └── is-extendable@1.0.1 
  │ │ │ │ │ └── pascalcase@0.1.1 
  │ │ │ │ ├─┬ debug@2.6.9 
  │ │ │ │ │ └── ms@2.0.0 
  │ │ │ │ ├─┬ define-property@0.2.5 
  │ │ │ │ │ └─┬ is-descriptor@0.1.6 
  │ │ │ │ │   ├─┬ is-accessor-descriptor@0.1.6 
  │ │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │ │   ├─┬ is-data-descriptor@0.1.4 
  │ │ │ │ │   │ └── kind-of@3.2.2 
  │ │ │ │ │   └── kind-of@5.1.0 
  │ │ │ │ ├── extend-shallow@2.0.1 
  │ │ │ │ ├── map-cache@0.2.2 
  │ │ │ │ ├── source-map@0.5.7 
  │ │ │ │ ├─┬ source-map-resolve@0.5.2 
  │ │ │ │ │ ├── atob@2.1.2 
  │ │ │ │ │ ├── decode-uri-component@0.2.0 
  │ │ │ │ │ ├── resolve-url@0.2.1 
  │ │ │ │ │ ├── source-map-url@0.4.0 
  │ │ │ │ │ └── urix@0.1.0 
  │ │ │ │ └── use@3.1.1 
  │ │ │ ├─┬ snapdragon-node@2.1.1 
  │ │ │ │ ├─┬ define-property@1.0.0 
  │ │ │ │ │ └─┬ is-descriptor@1.0.2 
  │ │ │ │ │   ├── is-accessor-descriptor@1.0.0 
  │ │ │ │ │   └── is-data-descriptor@1.0.0 
  │ │ │ │ └─┬ snapdragon-util@3.0.1 
  │ │ │ │   └── kind-of@3.2.2 
  │ │ │ ├── split-string@3.1.0 
  │ │ │ └─┬ to-regex@3.0.2 
  │ │ │   └─┬ safe-regex@1.1.0 
  │ │ │     └── ret@0.1.15 
  │ │ ├─┬ glob-parent@3.1.0 
  │ │ │ ├── is-glob@3.1.0 
  │ │ │ └── path-dirname@1.0.2 
  │ │ ├── inherits@2.0.3 
  │ │ ├─┬ is-binary-path@1.0.1 
  │ │ │ └── binary-extensions@1.12.0 
  │ │ ├─┬ is-glob@4.0.0 
  │ │ │ └── is-extglob@2.1.1 
  │ │ ├── lodash.debounce@4.0.8 
  │ │ ├─┬ normalize-path@2.1.1 
  │ │ │ └── remove-trailing-separator@1.1.0 
  │ │ ├── path-is-absolute@1.0.1 
  │ │ ├─┬ readdirp@2.2.1 
  │ │ │ ├── graceful-fs@4.1.15 
  │ │ │ └─┬ readable-stream@2.3.6 
  │ │ │   ├── core-util-is@1.0.2 
  │ │ │   ├── isarray@1.0.0 
  │ │ │   ├── process-nextick-args@2.0.0 
  │ │ │   ├── string_decoder@1.1.1 
  │ │ │   └── util-deprecate@1.0.2 
  │ │ └── upath@1.1.0 
  │ ├── fast-json-stable-stringify@2.0.0 
  │ └── source-map@0.7.3 
  ├── @angular-devkit/schematics@7.2.0 
  ├─┬ @schematics/angular@7.2.0 
  │ └── typescript@3.2.2 
  ├─┬ @schematics/update@0.12.0 
  │ ├── @yarnpkg/lockfile@1.1.0 
  │ ├── ini@1.3.5 
  │ ├─┬ pacote@9.1.1 
  │ │ ├── bluebird@3.5.3 
  │ │ ├─┬ cacache@11.3.2 
  │ │ │ ├── chownr@1.1.1 
  │ │ │ ├── lru-cache@5.1.1 
  │ │ │ ├─┬ move-concurrently@1.0.1 
  │ │ │ │ ├── aproba@1.2.0 
  │ │ │ │ ├─┬ copy-concurrently@1.0.5 
  │ │ │ │ │ └── iferr@0.1.5 
  │ │ │ │ ├── fs-write-stream-atomic@1.0.10 
  │ │ │ │ └── run-queue@1.0.3 
  │ │ │ └── y18n@4.0.0 
  │ │ ├── figgy-pudding@3.5.1 
  │ │ ├─┬ get-stream@4.1.0 
  │ │ │ └── pump@3.0.0 
  │ │ ├─┬ glob@7.1.3 
  │ │ │ ├── fs.realpath@1.0.0 
  │ │ │ ├─┬ inflight@1.0.6 
  │ │ │ │ └── wrappy@1.0.2 
  │ │ │ └── once@1.4.0 
  │ │ ├─┬ lru-cache@4.1.5 
  │ │ │ ├── pseudomap@1.0.2 
  │ │ │ └── yallist@2.1.2 
  │ │ ├─┬ make-fetch-happen@4.0.1 
  │ │ │ ├─┬ agentkeepalive@3.5.2 
  │ │ │ │ └── humanize-ms@1.2.1 
  │ │ │ ├── http-cache-semantics@3.8.1 
  │ │ │ ├─┬ http-proxy-agent@2.1.0 
  │ │ │ │ ├─┬ agent-base@4.2.1 
  │ │ │ │ │ └─┬ es6-promisify@5.0.0 
  │ │ │ │ │   └── es6-promise@4.2.5 
  │ │ │ │ └── debug@3.1.0 
  │ │ │ ├─┬ https-proxy-agent@2.2.1 
  │ │ │ │ └─┬ debug@3.2.6 
  │ │ │ │   └── ms@2.1.1 
  │ │ │ ├─┬ node-fetch-npm@2.0.2 
  │ │ │ │ ├── encoding@0.1.12 
  │ │ │ │ └── json-parse-better-errors@1.0.2 
  │ │ │ └─┬ socks-proxy-agent@4.0.1 
  │ │ │   └─┬ socks@2.2.2 
  │ │ │     ├── ip@1.1.5 
  │ │ │     └── smart-buffer@4.0.1 
  │ │ ├─┬ minimatch@3.0.4 
  │ │ │ └─┬ brace-expansion@1.1.11 
  │ │ │   ├── balanced-match@1.0.0 
  │ │ │   └── concat-map@0.0.1 
  │ │ ├─┬ minipass@2.3.5 
  │ │ │ └── yallist@3.0.3 
  │ │ ├─┬ mississippi@3.0.0 
  │ │ │ ├─┬ concat-stream@1.6.2 
  │ │ │ │ ├── buffer-from@1.1.1 
  │ │ │ │ └── typedarray@0.0.6 
  │ │ │ ├─┬ duplexify@3.6.1 
  │ │ │ │ └── stream-shift@1.0.0 
  │ │ │ ├── end-of-stream@1.4.1 
  │ │ │ ├── flush-write-stream@1.0.3 
  │ │ │ ├── from2@2.3.0 
  │ │ │ ├─┬ parallel-transform@1.1.0 
  │ │ │ │ └── cyclist@0.2.2 
  │ │ │ ├─┬ pumpify@1.5.1 
  │ │ │ │ └── pump@2.0.1 
  │ │ │ ├── stream-each@1.2.3 
  │ │ │ └─┬ through2@2.0.5 
  │ │ │   └── xtend@4.0.1 
  │ │ ├─┬ mkdirp@0.5.1 
  │ │ │ └── minimist@0.0.8 
  │ │ ├─┬ normalize-package-data@2.4.0 
  │ │ │ ├── hosted-git-info@2.7.1 
  │ │ │ ├─┬ is-builtin-module@1.0.0 
  │ │ │ │ └── builtin-modules@1.1.1 
  │ │ │ └─┬ validate-npm-package-license@3.0.4 
  │ │ │   ├─┬ spdx-correct@3.1.0 
  │ │ │   │ └── spdx-license-ids@3.0.3 
  │ │ │   └─┬ spdx-expression-parse@3.0.0 
  │ │ │     └── spdx-exceptions@2.2.0 
  │ │ ├─┬ npm-package-arg@6.1.0 
  │ │ │ └─┬ validate-npm-package-name@3.0.0 
  │ │ │   └── builtins@1.0.3 
  │ │ ├─┬ npm-packlist@1.2.0 
  │ │ │ ├── ignore-walk@3.0.1 
  │ │ │ └── npm-bundled@1.0.5 
  │ │ ├── npm-pick-manifest@2.2.3 
  │ │ ├─┬ npm-registry-fetch@3.8.0 
  │ │ │ └─┬ JSONStream@1.3.5 
  │ │ │   └── jsonparse@1.3.1 
  │ │ ├─┬ osenv@0.1.5 
  │ │ │ ├── os-homedir@1.0.2 
  │ │ │ └── os-tmpdir@1.0.2 
  │ │ ├── promise-inflight@1.0.1 
  │ │ ├─┬ promise-retry@1.1.1 
  │ │ │ ├── err-code@1.1.2 
  │ │ │ └── retry@0.10.1 
  │ │ ├─┬ protoduck@5.0.1 
  │ │ │ └── genfun@5.0.0 
  │ │ ├── rimraf@2.6.3 
  │ │ ├── safe-buffer@5.1.2 
  │ │ ├── semver@5.6.0 
  │ │ ├── ssri@6.0.1 
  │ │ ├─┬ tar@4.4.8 
  │ │ │ ├── fs-minipass@1.2.5 
  │ │ │ └── minizlib@1.2.1 
  │ │ ├─┬ unique-filename@1.1.1 
  │ │ │ └─┬ unique-slug@2.0.1 
  │ │ │   └── imurmurhash@0.1.4 
  │ │ └─┬ which@1.3.1 
  │ │   └── isexe@2.0.0 
  │ └── semver-intersect@1.4.0 
  ├─┬ inquirer@6.2.1 
  │ ├── ansi-escapes@3.1.0 
  │ ├─┬ chalk@2.4.2 
  │ │ ├─┬ ansi-styles@3.2.1 
  │ │ │ └─┬ color-convert@1.9.3 
  │ │ │   └── color-name@1.1.3 
  │ │ ├── escape-string-regexp@1.0.5 
  │ │ └─┬ supports-color@5.5.0 
  │ │   └── has-flag@3.0.0 
  │ ├─┬ cli-cursor@2.1.0 
  │ │ └─┬ restore-cursor@2.0.0 
  │ │   ├─┬ onetime@2.0.1 
  │ │   │ └── mimic-fn@1.2.0 
  │ │   └── signal-exit@3.0.2 
  │ ├── cli-width@2.2.0 
  │ ├─┬ external-editor@3.0.3 
  │ │ ├── chardet@0.7.0 
  │ │ ├─┬ iconv-lite@0.4.24 
  │ │ │ └── safer-buffer@2.1.2 
  │ │ └── tmp@0.0.33 
  │ ├── figures@2.0.0 
  │ ├── lodash@4.17.11 
  │ ├── mute-stream@0.0.7 
  │ ├─┬ run-async@2.3.0 
  │ │ └── is-promise@2.1.0 
  │ ├─┬ string-width@2.1.1 
  │ │ ├── is-fullwidth-code-point@2.0.0 
  │ │ └─┬ strip-ansi@4.0.0 
  │ │   └── ansi-regex@3.0.0 
  │ ├─┬ strip-ansi@5.0.0 
  │ │ └── ansi-regex@4.0.0 
  │ └── through@2.3.8 
  ├─┬ opn@5.3.0 
  │ └── is-wsl@1.1.0 
  ├── semver@5.5.1 
  └── symbol-observable@1.2.0 

npm WARN optional Skipping failed optional dependency /@angular/cli/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

how to solve ?
please explain

**Comment by billchurch** [comment]
duplicate #123
