### ISSUE TITLE
suport :privateKey

### ISSUE THREAD

**Issue by hktalent** [billchurch/WebSSH2#124]
var os = require('os'),fs = require('fs');
![image](https://user-images.githubusercontent.com/18223385/50972910-ae5e5580-1522-11e9-8713-821b7dfaae3a.png)

 req.session.ssh = 
    {
        privateKey: fs.readFileSync(os.userInfo().homedir + config.privateKey),

conn.connect({
      privateKey: socket.request.session.ssh.privateKey,
.......
      debug: debug('ssh2')
    })

![image](https://user-images.githubusercontent.com/18223385/50972980-cfbf4180-1522-11e9-9068-0aaf9c1bbd20.png)

**Comment by hktalent** [comment]
set privateKey
not pass,can not connect?

**Comment by hktalent** [comment]
fix:
socket.js
```
var oSs = socket.request.session,oSsh = oSs.ssh;
if (oSs.username && oSsh && (oSs.userpassword || oSsh.privateKey)) {
```

**Comment by V-Grade** [comment]
It's realy work ? How you did it ? I need that too ^^
