### ISSUE TITLE
connect multiple ip addresses

### ISSUE THREAD

**Issue by chengpengvb** [billchurch/WebSSH2#131]
It seems that only one ssh connection of ip address can be opened on the same browser, hoping to support multiple IPs.

**Comment by sangmeshcp** [comment]
+ 1 .. I'm also lookig for the same ..

**Comment by billchurch** [comment]
I'm not sure why you're seeing this. I have installations where this is not the case. How are you providing the host information to the app? via config file?

This is the most recent version, and as long as you specify the host from the URL you can connect to as many systems as you want. 
![image](https://user-images.githubusercontent.com/1668075/57224309-0d1a7400-6fd7-11e9-90d4-38c967a359e0.png)

**Comment by billchurch** [comment]
I misunderstood your statement, however I tested two connections to the same device and that works as well... 

![image](https://user-images.githubusercontent.com/1668075/57224541-c9743a00-6fd7-11e9-9b1d-6626bcf1b2f5.png)


You may need to enable this option: 
![image](https://user-images.githubusercontent.com/1668075/57224496-a6e22100-6fd7-11e9-954e-2751886d6256.png)

In config.json

**Comment by chengpengvb** [comment]
Thanks to your guidance, I solved my problem, thank you very much for your work.
