### ISSUE TITLE
Additional option ssh.remoteCommand to execute a command once the shell is running

### ISSUE THREAD

**Issue by Utopiah** [billchurch/webssh2#132]
Something like `if (ssh.remoteCommand) stream.write(ssh.remoteCommand+"\n")` in [connShell](https://github.com/billchurch/WebSSH2/blob/master/app/server/socket.js#L51)

Motivated by using screen thus always doing `screen -raAD` on connection, related discussion https://github.com/mscdex/ssh2/issues/769 and previous issue on `-t` https://github.com/billchurch/WebSSH2/issues/57

**Comment by billchurch** [comment]
Are you looking to use "exec" or "shell" method for this?

**Comment by Utopiah** [comment]
As mentioned in the ssh2 issue those methods didn't seem to work hence ended up using `write()`. Might have to distinguish non interactive vs interactive commands.
