### ISSUE TITLE
Incompatible with F5 v14+

### ISSUE THREAD

**Issue by smilam** [billchurch/webssh2#136]
This project cannot be imported to F5 BIG-IP v14 and higher. Any chance it's going to be updated for compatibility, or any chance a future release of F5 will allow for backwards compatibility for projects that are still tcl based? 
Thanks Bill.

**Comment by billchurch** [comment]
@smilam there is work to bring this functionality native to BIG-IP at some point. contact me at bill@f5.com for more info.
