### ISSUE TITLE
is it possible to include the username as a get request var?

### ISSUE THREAD

**Issue by ronny-vandenbroeck-excentis** [billchurch/webssh2#139]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
  - `npm -v`
- Server OS Version / Distribution / Processor Architecture
  - `uname -a`
  - `cat /etc/os-release`
- WebSSH2 release version
  - `grep version app/package.json`
- OS and Version of SSH server connecting to
  - `uname -a`
  - `sshd -v`
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output

**Comment by billchurch** [comment]
Explain your use-case a bit. Username with no password as a GET var?

**Comment by ronny-vandenbroeck-excentis** [comment]
Hi Bill, yes that would be useful.
I'm writing technical documentation, and would like to include hyperlinks in my documentation that allow my readers to connect via ssh to a server, without having to supply the username, but rather only the password, or key authentication.
First question is if it would be possible to include the username in the hyperlink ...
second question is if it would also be possible to use key authentication ...
Third, since currently i'm making use of unsecured http connections is, how I would secure my docker container by using https

**Comment by ronny-vandenbroeck-excentis** [comment]
node: v8.6.0
npm: 5.3.0
uname -a: Linux 24e23b210ed7 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
OS Release: PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by msherman64** [comment]
I have a similar use case. 
I have a ssh jump host that my users authenticate to, and then many ephemeral machines that are mostly accessed as the root user from there. 
Many users push new keys or passwords to these temporary machines, so it's important that the web request operate the same as the command line operation.

**Comment by cron410** [comment]
I would also like to see this feature. It would greatly help me for integrating this with LibreNMS or whatever other management system people use. Both Chrome and Opera seem to cache the credentials making it sometimes impossible to log into things in my testing.

**Comment by billchurch** [comment]
I think #85 covers this use case.

If you add a username object to /get then you still need to collect the password. Since we don't have a modal method for that yet we'd need to build that. 

See #159 and #160 and vote for them. will work to build them after we can workout the use case and the design.
