### ISSUE TITLE
alternative auth

### ISSUE THREAD

**Issue by zenion** [billchurch/WebSSH2#14]
basic auth in most browsers is really annoying because it saves the auth credentials based on the subdomain. meaning that when i connect to server A with credentials A, all is good... but then when i go to connect to server B it automatically tries to pass credentials A and doesn't prompt me again. Worse yet, if someone clicks cancel on basic auth prompt, it keeps passing NO credentials and webssh2 will just see a connection attempt without session.username/password.

Any ideas on how I could maybe replace basic auth with a forms based overlay perhaps?

**Comment by zenion** [comment]
maybe like a modal overlay would suffice?

**Comment by billchurch** [comment]
Good call. I've been considering this use case. Right now the main entry point for this app (for my use case) is a system which does SSO, so the browser isn't part of basic auth. I'd definitely accept a pull request on this feature, otherwise I'll put it on the feature request list and will get to it eventually.

**Comment by billchurch** [comment]
@zenion, thoughts on these ideas:

4 methods of authentication:
1 - Modal/Prompt 
2 - POST vars
3 - GET vars (horrible idea)
4 - HTTP Basic (current)

Add a variable to [WebSSH2/config.json](https://github.com/billchurch/WebSSH2/blob/master/config.json) to indicate which authentication method is in use.

**Comment by zyysasuke** [comment]
@billchurch I had a problem about authentication. I want to automatically login to a server so I put the username and password in the config.json. However, I still got prompt to ask me to enter username and password.
