### ISSUE TITLE
SSH CONN ERROR: connect ECONNREFUSED 127.0.0.1:22

### ISSUE THREAD

**Issue by handyzhang** [billchurch/webssh2#140]
Excuse me
chrome-page:
1、Input control can not input
2、Menu cannot be opened
3、SSH CONN ERROR: connect ECONNREFUSED 127.0.0.1:22
so? i should to do.   I am a newbie.

clone code，npm install ，and npm start  ，open page
windows 10

**Comment by billchurch** [comment]
Do you actually have an ssh server listening on 127.0.0.1 port 22 on windows 10?

**Comment by handyzhang** [comment]
oh，My local ssh server is broken.
so,after changing to ssh on the server, it succeeded.
thank you.
