### ISSUE TITLE
how to change x-term font size?

### ISSUE THREAD

**Issue by ciey** [billchurch/webssh2#142]

**Comment by billchurch** [comment]
Modify the .js and run `npm run build`

This is a list of options for xterm.js:

https://xtermjs.org/docs/api/terminal/classes/terminal/#setoption

The quick and dirty way:
You can add a line right before here:
https://github.com/billchurch/webssh2/blob/1cbb1957397449a7bda1a7636f4dda4c6efe2aa5/app/client/src/js/index.js#L30

Which looks something like this:

```
term.setOption('fontSize', 40)
term.open(terminalContainer) 
```

there are other options you can set as well. See in the xterm.js docs link above.

Another way you could do it, is set it from the server side, but that would take a bit more work. 

This block of code is for setting some options which are controlled from the server:
https://github.com/billchurch/webssh2/blob/1cbb1957397449a7bda1a7636f4dda4c6efe2aa5/app/client/src/js/index.js#L67-L72

You could add the options you want here, `npm run build` and a corresponding spot in the server side code:
  'terminal': {
    'cursorBlink': true,
    'scrollback': 10000,
    'tabStopWidth': 8,
    'bellStyle': 'sound'
  },

Something like that...
