### ISSUE TITLE
How do I use x11 forwarding with web based ssh

### ISSUE THREAD

**Issue by SwapnilBhatkar** [billchurch/webssh2#143]
I'm trying to run a GUI based application on a remote server. For that I need to use x11 forwarding. How can I do it on a web-based ssh?

I have x11 server hosted on my remote machine. I also changed the sshd config file. 
x11 forwarding yes. Please help

**Comment by billchurch** [comment]
Not really a way to do this without some kind of client-side component. The browser sandbox in all browsers prevent direct network connection from a websocket or something in the browser, which is what would be required.
