### ISSUE TITLE
no such file or directory, open '/usr/local/WebSSH2/package.json'

### ISSUE THREAD

**Issue by HakunamatataLeo** [billchurch/webssh2#147]
![image](https://user-images.githubusercontent.com/4550421/63247791-79746700-c298-11e9-9601-c6c4f8d63aae.png)

**Comment by billchurch** [comment]
Type this in and send me the output:
```
pwd
ls .
```

**Comment by ISYS-Root** [comment]
You need to go to the webssh2/app directory.
And now you run the npm install in the directory webssh2
