### ISSUE TITLE
get unZip for webssh2.bundle.js  

### ISSUE THREAD

**Issue by englishhk** [billchurch/webssh2#148]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
  - `npm -v`
- Server OS Version / Distribution / Processor Architecture
  - `uname -a`
  - `cat /etc/os-release`
- WebSSH2 release version
  - `grep version app/package.json`
- OS and Version of SSH server connecting to
  - `uname -a`
  - `sshd -v`
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output

**Comment by billchurch** [comment]
If what you're asking is the unminified code, you can just do a "npm run builddev" its packed with webpack.
