### ISSUE TITLE
What is the cause of this problem?

### ISSUE THREAD

**Issue by ws615405105** [billchurch/webssh2#149]
This error occurred after starting the project, but it also happens occasionally ---Error: ENOENT: no such file or directory, stat 'D:\WorkSpace\IWorkSpace\webssh2\app\client\public\client.htm'

**Comment by billchurch** [comment]
Not sure I've seen that before. the file exists?

**Comment by ws615405105** [comment]
I found the problem. After I modified the project, public can be lost, only src is left, thank you.

**Comment by ws615405105** [comment]
I want to embed this project into the Vue project. Do you have any good suggestions? I have tried it and there is no result.

**Comment by lijiahao8898** [comment]
i also want to embed this project into the Vue project. :)

**Comment by billchurch** [comment]
it would be nice if there was an easy way to just drop this in a project, but code probably has to be refactored and this more than likely turned into a module...
