### ISSUE TITLE
How to automatically write code in the terminal?

### ISSUE THREAD

**Issue by Jan1900** [billchurch/webssh2#170]
Hello,
I'm pretty new to using socket.io and xterm, so forgive me if I there is something I'm missing.

I am trying to embed webssh2 in a wesbite for a project at university. Now that I've done that the next step would be, to have a code snippet from the website automatically written in the terminal once you've clicked on it. So basically just like using katacoda.com.

Now I now how to make a code snippet clickable, so my question is: Where exactly do I need to implement a function that recieves the text from the code snippet and writes it in the terminal? I've looked into the socket.js file and I suppose it would be done there with some sort of stream.write but I can't figure out where exactly.

Thank you in advance for your help.

**Comment by billchurch** [comment]
Well, from the client-side you can do "socket.emit('data', 'blah blah blah')"

https://github.com/billchurch/webssh2/blob/2289036605d57f000585c2320790122218e15015/app/client/src/js/index.js#L54-L56

Something like that would do it, but most likely you'd want this to happen from the server side, it's a bit out of scope here and could get pretty complicated...
