### ISSUE TITLE
delete key only work when press shift + delete in some devices

### ISSUE THREAD

**Issue by zyysasuke** [billchurch/webssh2#171]
The system related version shows below  
- `node -v` --> v11.10.0
  - `npm -v` --> 6.7.0
  - `uname -a` --> Linux webssh-server 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 (2017-12-13) x86_64 GNU/Linux
  - `cat /etc/os-release` 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
- WebSSH2 release version
  - `grep version app/package.json` --> "version": "0.2.8"
- OS and Version of SSH server connecting to
  - `sshd -v` --> OpenSSH_6.7p1 Debian-5+deb8u7, OpenSSL 1.0.2l  25 May 2017

Hi author,
I am glad you offer such a great project.
In most cases, webssh2 works very well.  However, when I use webssh2 to log into some switches, delete key only works when I press shift + delete. I do not know if this is a device-related problem or webssh2 problem

**Comment by billchurch** [comment]
>  I do not know if this is a device-related problem or webssh2 problem

If you use Putty on those devices, do you have to press shift+delete ?

What TERM variable does that device expect?
