### ISSUE TITLE
[FAQ] access remotely my system using my.openHAB

### ISSUE THREAD

**Issue by kirantpatil** [billchurch/webssh2#172]
Hi,

I would like to access remotely my system using my.openHAB using webssh2.

Is it possible since my system is connected to my.openHAB ?

Thanks.

**Comment by billchurch** [comment]
Anything is possible. You would need to "publish" the web page of WebSSH2 somewhere... Probably not the most secure thing in the world to do... This is all possible, but out of the scope of this project.
