### ISSUE TITLE
I need button and send text

### ISSUE THREAD

**Issue by Mahani9271** [billchurch/webssh2#174]
hi , thanks for code , u r very good man 

i need your help , pls tel to me how i can create button and send command with that button with js
sample i try code 
\<body>
  \<div class="box">
    \<div id="header"></div>
    \<div id="terminal-container" class="terminal"></div>
    \<div id="bottomdiv">
      \<div id="txt">
     \   <input type="button" onclick="mm()" value="ss">
      \</div>
      \<div class="dropup" id="menu">
      \  <i class="fas fa-bars fa-fw"></i> Menu
        \<div id="dropupContent" class="dropup-content"></div>
      \</div>
      \<div id="footer"></div>
     \ <div id="status"></div>
    \</div>
  \</div>
<script src="/webssh2.bundle.js" defer></script>

<script>
  function mm(){
    var term = new Terminal();
    term.open(document.getElementById('terminal-container'));
    term.write('top')
  }
</script>"

pls help me

**Comment by billchurch** [comment]
This is not really the forum for these types of questions. If you wish to modify how this app works, it's understood that you would have some sort of development background and familiarity with HTML5 + Javascript to make those changes. 

The events are pretty well labeled in [app/client/src/js/index.js](https://github.com/billchurch/webssh2/blob/master/app/client/src/js/index.js). 

You probably want your function to do something like: 

  `socket.emit('data',  somedata)`

Which would send the contents of the variable _somedata_ to the SSH host. 

This is an example function that tells the WebSSH2 server to replay the credentials to the client. This is called with an `onClick` function to a button that's rendered on the HTML5 front-end.

https://github.com/billchurch/webssh2/blob/42f973b4796f7f50237dc8ce613e477aa89352ca/app/client/src/js/index.js#L180-L186

That's about all the help I can offer for this. Stackoverflow might be a better venue for your question.
