### ISSUE TITLE
User/password support in url

### ISSUE THREAD

**Issue by Naprogramuji** [billchurch/webssh2#178]
Is there way to pass username and password for SSH connection using url address itself? We are using this in our internal administration. So when our administrator is logged in and opens special webpage with webssh2 in iframe, he will be logged automatically.

**Comment by dongping8887** [comment]
we need it too!

**Comment by billchurch** [comment]
Interested in taking a PR for this, but it's not something on my roadmap at this time.

**Comment by evgeniymx** [comment]
+1 for this feature

**Comment by jbelleza29** [comment]
+1 for this one.

**Comment by bartekkoks** [comment]
+1 for this feature

**Comment by YashonNice** [comment]
+1 for this feature

**Comment by pmartini82** [comment]
+1 for this feature

**Comment by pmartini82** [comment]
where can we donate?

**Comment by l455435655** [comment]
+1 for this feature

**Comment by billchurch** [comment]
so, i'm on the fence on this one. exposing the password on the URL isn't great... especially for an administrative system... going to close for now, but willing to discuss a more secure way to implement this.
