### ISSUE TITLE
How to change the prompt under authorization

### ISSUE THREAD

**Issue by xiaoyong513** [billchurch/webssh2#179]
For the first login, the prompt under the required authorization is used for changeability?

**Comment by xiaoyong513** [comment]
For the first login, the prompt under the required authorization is used for changeability?

**Comment by billchurch** [comment]
I'm not quite sure what you're asking for here. Do you want to change the method from HTTP Basic auth to something else? Or what exactly?

**Comment by xiaoyong513** [comment]
My English is terrible, 
![TIM图片20200309150611](https://user-images.githubusercontent.com/30016438/76190305-a5950c80-6217-11ea-97e0-99e475340ad4.png)

**Comment by xiaoyong513** [comment]
![TIM图片20200309150611](https://user-images.githubusercontent.com/30016438/76190355-c4939e80-6217-11ea-801f-048ef960d9fa.png)

**Comment by xiaoyong513** [comment]
![123](https://user-images.githubusercontent.com/30016438/76190827-e17ca180-6218-11ea-962b-abfc57551b79.png)

**Comment by xiaoyong513** [comment]
![123](https://user-images.githubusercontent.com/30016438/76190848-f0fbea80-6218-11ea-8e61-7170250c4e89.png)

**Comment by billchurch** [comment]
This is a browser behavior issue and out of scope for this project
