### ISSUE TITLE
how to reappear username and password pop-up ,not restart the browser to reappear

### ISSUE THREAD

**Issue by chenxiweiyang-ing** [billchurch/webssh2#181]
After I  entered the wrong username and password,the password username pop-up will not appear again.i want the pop-up to appear again,not restart the browser to reappear.I tried something,but  it didn't work

**Comment by billchurch** [comment]
See issue #51 and pull #85 for the "reauth" feature you can enable.

**Comment by chenxiweiyang-ing** [comment]
But it didn't work,After I entered the wrong username and password in Google browser,The website stays at  '/reauth'.And Switch between the '/reauth' and 'ssh/host/hostname' in firefox browser.The pop-up didn't reappear.
I think the problem is basictAuth in 'util.js', 'req.session.userpassword' is still exsit, so the pop-up didn't reappear.How to clear it?Do you have the same problem as me?

**Comment by phunghop** [comment]
same issue

**Comment by todaygood** [comment]
same issue
