### ISSUE TITLE
I also have some  problems about#181 

### ISSUE THREAD

**Issue by chenxiweiyang-ing** [billchurch/webssh2#182]
But it didn't work,After I entered the wrong username and password in chrome,The website stays at '/reauth'.And Switch between the '/reauth' and 'ssh/host/hostname' in firefox .The pop-up didn't reappear.I think that is because browser remember basic-auth with my wrong password。
I think the problem is basictAuth in 'util.js',
“if (myAuth && myAuth.pass !=='')”，
'myAuth.pass' is still exsit, so the pop-up didn't reappear.How to clear it?Do you have the same problem as me?
chrome：‘ 80.0.3987.122’
firefox：‘73.0.1’

**Comment by ukus04** [comment]
I want clear it everytime.
I can't connect to another host, because username and password are saved.
But, I can't find where to edit in source code..
