### ISSUE TITLE
Suggestion: Safe shutdown

### ISSUE THREAD

**Issue by edgarogh** [billchurch/webssh2#186]
When I shut down my **webssh2** instance, I always fear that there are still users connected to SSH, who would lose their connection (and their work). My idea is that when a SIGINT (Ctrl + C) signal is sent to the server, it intercepts it (doesn't immediately stops) and enters a "Shutdown mode".

**As soon as the server goes in shutdown mode:**
 * _Incoming HTTP requests aren't accepted anymore_, or are politely declined with an appropriate error message (i.e. `503 - Service unavailable`)
 * _A countdown of x (configurable) seconds start_, and every single connected client receives a message notifying them of the future server shutdown. All clients can see a live countdown on the Web UI, and may save their work or do whatever's best for them
 * When the countdown reaches 0, the server stops normally
 * If all clients disconnect before the end of the countdown, the server doesn't need to wait and stops immediately
 * The server admin should have the last word: _if a second SIGINT is sent, the server stops wether or not some clients are still connected_

**Things to take into consideration:**
 * #76 : This issue suggests a way to keep sessions open. If the sessions are managed through `tmux` or `screen`, they can persist across server restarts and don't depend on the **webssh2** process. If this suggestion is implemented:
   - Does the server stop immediately, since sessions can be recovered ?
   - Does it still wait in order not to surprise the user ?
 * ~~Should "shutdown mode" be cancellable or not (i.e. by pressing a key) ? I don't know if - according to the UNIX spec - a program should be able to recover from a SIGINT, even though that's technically possible~~ My shell, fish, sends a SIGTERM shortly after the second SIGINT, so I assume we're not supposed to "cancel" the shutdown mode

_Due to the lockdown where I live, I have time to work on this if you're interested._

**Comment by billchurch** [comment]
Great idea for an enhancement. Would be happy to take a PR for this.
