### ISSUE TITLE
Support copy/paste

### ISSUE THREAD

**Issue by kalagxw** [billchurch/webssh2#188]
I'm not very familiar with macs or mac keyboards. 、we can't do ^C or ^V for anything, obviously they need to be passed to the terminal. There's no way to rebind copy/paste functionality to a different key combination inside a browser. The best you're going to get is` select text +( right-click)= copy` and `right click = paste`.

**Comment by billchurch** [comment]
Mac users CMD+C and CMD+V for cut and paste and that works fine. 

For windows, binding an additional key (CTRL+SHIFT+C for example) could be accomplished, however this is a problem in ANY terminal that recognizes CTRL-C as SIGINT, so it’s not unique to this project or xterm.js. 

See this issue on xterm.js: https://github.com/xtermjs/xterm.js/issues/1868

If this is something we want to implement, just need to come up with a design and someone to test.
