### ISSUE TITLE
integrate Webssh2 with Django project

### ISSUE THREAD

**Issue by aabuali** [billchurch/webssh2#189]
Hello,

I'm using webssh2 and want to integrate it with django project.

is there any way to make webssh one of the django apps.

or at least make web ssh use same django port. the concern here is I dont want to open 2 ports for the project(one for django and other for webssh).

currently I'm using ifram to include webssh links inside django pages and in this case both ports need to be opened.

Regards

**Comment by billchurch** [comment]
I would recommend using a proxy (NGINX, Haproxy, something like that) for this integration, with redirects for requests to /ssh to the webssh container ingress ports and everything else handled by your Django project ingress port(s). From the client side, everything would appear to come from same server/port.
