### ISSUE TITLE
RFE: BIG-IP iRulesLX Version of Code

### ISSUE THREAD

**Issue by qadv** [billchurch/webssh2#193]
Hey Bill,

Awesome stuff! been using this for a while now.

Currently looking to integrate it with the SSH Proxy to allow for BIG-IP rules to be introduced.

Is there any chance you have done this?

Final Question - I am also looking at transitioning to kerberos authentication as well, any work done in this area?

NK

**Comment by billchurch** [comment]
Right now there are no plans for a public implementation of this. While you could make it work with iRules LX it's pretty complicated and not supported by this project. 

I do know that F5 Professional Services have implemented this feature for customers, but it would be a paid engagement.

This would probably make more sense as a separate project, reason being that iRules LX is pretty much locked in at nodejs v6 and we're starting to run out of runway to support that version of nodejs

**Comment by billchurch** [comment]
since BIG-IP continues to be stuck in Node v6, have to abandon this feature request for this project.
