### ISSUE TITLE
Cannot open password/username pop-up if entered wrong username or password

### ISSUE THREAD

**Issue by phunghop** [billchurch/webssh2#194]
Hi Bill,

After entered wrong username or password
Google Chrome: redirect to http://localhost:2222/ssh/reauth
Firefox: website stay http://localhost:2222/ssh/host/ip and refresh interval
![image](https://user-images.githubusercontent.com/14747286/78776388-fd16cb80-79c1-11ea-85c3-b057c01c04fa.png)

=> The password/username pop-up din't reappear

**Comment by billchurch** [comment]
See #196
