### ISSUE TITLE
Switch User not woking in FireFox

### ISSUE THREAD

**Issue by phunghop** [billchurch/webssh2#196]
Click Switch User in FireFox 
The password/username pop-up din't appear

**Comment by billchurch** [comment]
For whatever reason, Firefox continues to cache and resubmit the basic auth credentials, even after a failure.

You can test this by connecting to a host with invalid credentials, Firefox and Safari will forever try to authenticate after a 401. Chrome seems to work properly...

![image](https://user-images.githubusercontent.com/1668075/93462535-7b05c980-f8b4-11ea-91d6-5cfc34270bfb.png)

For now, it looks like only Chrome supports this feature.

**Comment by Utopiah** [comment]
Indeed... I tried clearing up cookies in Firefox but to no avail. It does work in private mode though. Interestingly enough it fails in another container in the same user session.

**Comment by billchurch** [comment]
will be addressed with an alternate credentialing method in future release (0.5.0) see #244

**Comment by skorpions2000** [comment]
Hello, I am trying use the webssh on Firefox, and no work switch user button. I can do something then that will be repaired it? 
Thank you for answer

**Comment by skorpions2000** [comment]
> sth.ssh.utopiah.com
@Utopiah I try your idea but no worked for me
@billchurch

**Comment by Utopiah** [comment]
@skorpions2000 strange that the other subdomain didn't prompt for a new login. Are you sure you visited the new sub domain?

**Comment by skorpions2000** [comment]
> @skorpions2000 strange that the other subdomain didn't prompt for a new login. Are you sure you visited the new sub domain?

It's work only after create new subdomian, after first login i can connect only one server, when i put in another server on address line i will be reconnected all the time. And when cleaning cookie, it no help on Firefox. But on mobile Firefox on Android when cleaning cookies it's helping retype new authentication for new servers.
