### ISSUE TITLE
Iframe starts to request the website server.

### ISSUE THREAD

**Issue by hawk-01** [billchurch/webssh2#197]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
12.X
- Server OS Version / Distribution / Processor Architecture
  Linux
- WebSSH2 release version
0.3.1-pre-release-0.0
- OS and Version of SSH server connecting to
Linux 
OpenSSH_7.9p1
- Browser Version and OS
Chrome 
When i try to iframe in into my local website it starts to request the localhost of the framework server and it fails 

![image](https://user-images.githubusercontent.com/52874528/81870712-151ad580-9594-11ea-9e70-25c1102e117d.png)

  Is there a soloution

**Comment by billchurch** [comment]
Not really inscope for this project as this is more general about web design and programming. Recommend expanding those errors and seeing what the real issue is. Could be security related but hard to tell from that screenshot.
