### ISSUE TITLE
Use hostname instead of IP in URL

### ISSUE THREAD

**Issue by nebuchad908** [billchurch/webssh2#199]
Hello.

If subnets array "allowedSubnets" contains any subnets, then URL 

http://a.d.d.r:2222/ssh/host/host.name?port=1234 not working  with error 401 UNAUTHORIZED

when I change host.name to their IP, session works fine.

**Comment by billchurch** [comment]
Good point, there's definitely no rectification between hostname and the allowedSubnets feature. Will add this to the list of bug/enhancements for the next release.

**Comment by nebuchad908** [comment]
Nice. I think it's easy to resolve IP of requested hostname and use it. Thanks!

**Comment by billchurch** [comment]
Yeah, should be easy to solve no doubt...

**Comment by billchurch** [comment]
fixed in #234
