### ISSUE TITLE
client (public) into IIS

### ISSUE THREAD

**Issue by sureshkumarramu** [billchurch/WebSSH2#20]
Hi Bill Church,

Excellent implementation. 

Is it possible to split the client (public) part from node.js to some other language? Say dotnet (iis) or java.

I try copy the “public” folder and put it under IIS web site, changed the socket connection to “socket = io.connect('http://localhost:2222/socket.io/')” But this is not working! 

Can you please guide how to unplug the client part from node.js and put it in different platform?

Thanks

**Comment by billchurch** [comment]
The client part is based on xterm.js, you should really start there instead of trying to work backwards from this project
