### ISSUE TITLE
auto login in with username

### ISSUE THREAD

**Issue by xiutuo** [billchurch/webssh2#215]
I want to specify a username to auto-login with webssh(all the client use the same rsa key file but different user), with below url
http://localhost:2222/ssh/host/192.168.1.1?username=root&port=2244&header=My%20Header&headerBackground=red

edit WebSSH2/server/socket.js add new line at the head 
var fs = require('fs');

I had change to test it,workout fine for me
privateKey: socket.request.session.privatekey --->privateKey: fs.readFileSync('/root/.ssh/id_rsa')
 username: socket.request.session.username -- -> username: 'root', 

how to edit the server/app.js file  to add the new parameter "username" ?

**Comment by rushabh-wadkar** [comment]
I don't know what @billchurch will suggest, however, If I would make any changes for this (for my own) then I would follow below steps - 

1. In app.js, remove `app.use(myutil.basicAuth)` (this just removes the alert box middleware)

2. Again in app.js, inside `app.get("/ssh/host/:host?"` route function, before rendering client.htm file, insert
 ` req.session.username = req.query.username;`
`req.session.privatekey = fs.readFileSync('/root/.ssh/id_rsa')`

This would replace the basic auth functionality and would use username from GET header and private key from /root/,ssh/id_rsa  file and set itself in req.session vars.

**Comment by xiutuo** [comment]
thanks @rushabh-wadkar !I will try it.
it's show error:

{code: 1, message: "Session ID unknown"}
code: 1
message: "Session ID unknown"

**Comment by billchurch** [comment]
same as #243, check out [0.4.0-testing-2](https://github.com/billchurch/webssh2/releases/tag/0.4.0-testing-2) for a solution, this will be released in 0.4.0 due out shortly.
