### ISSUE TITLE
Logging out of the device after turning off the tab (not after close browser)

### ISSUE THREAD

**Issue by dawbit** [billchurch/webssh2#216]
What do I need to change in the code so that the user's session is deleted when the tab is closed in the browser, not the entire browser? It is a bit dangerous. Currently, after opening the same address, for example:
http://ocalhost:2222/ssh/host/test.com
after closing the card, by entering the same address, he immediately logs in with the previous permissions. I would like the login details window to appear again in this case.

**Comment by billchurch** [comment]
What you’re seeing is the browser caching basic auth. Navigating to “/ssh/reauth” should invalidate this, but it will request new credentials.

**Comment by dawbit** [comment]
> 
> 
> What you’re seeing is the browser caching basic auth. Navigating to “/ssh/reauth” should invalidate this, but it will request new credentials.

But, using the onbeforeunload event, I can't redirect to another page because the browsers block it. Is there any solution to this problem?

**Comment by billchurch** [comment]
Thinking through this... If we invalidate a session on the webssh2 side, a new connection will get an HTTP 401, the browser will send the last known credentials to the webssh2 side...which will be successful...

Basic Authentication is really the enemy here, I think what this calls for is a different authentication technique. Any other thoughts?

**Comment by sergio737373** [comment]
Hello, there is a way to modify the code so that the username and password are not saved in the browser cookie. I need you not to save the credentials to connect to a switch with different users and for security. From already thank you very much!!

**Comment by billchurch** [comment]
This isn't being saved in a cookie, the browser is saving it and it won't let go until you close the browser or open an in-private session.

Chrome will honor an HTTP 401 response and drop credentials and request new credentials from the user however Firefox will not. 

I'm working on a new authentication system that does not use HTTP Basic Authentication which should resolve this issue.

**Comment by sergio737373** [comment]
I understand, just in case I will comment again, I don't know if I explained well, what I need is that when closing the browser tab or whenever there is a connection, ask for the credentials. I await the new authentication system. I thank you a lot for the prompt response and help.

**Comment by sergio737373** [comment]
Estimated:
Last query, I tried to enable the backspace clear key on the "control-H" switches and I had no luck. You could tell me how to enable the delete key of the X-term. Again thank you very much!!

**Comment by billchurch** [comment]
try sending credentials via POST request instead of HTTP BASIC. You can see #290 for more information here. This will be released in 0.4.7, but right now you can pre-view this in one of the 0.4.7-alpha tags.
