### ISSUE TITLE
socket.io security issue

### ISSUE THREAD

**Issue by ganisback** [billchurch/webssh2#222]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - v14.15.4
  - 6.14.10
- WebSSH2 release version
    "version": "0.2.10-1",
    "release": "standard-version"
    "standard-version": "^7.0.0",
- OS and Version of SSH server connecting to
  - Linux ib21b13 3.10.0-1160.2.2.el7.x86_64 #1 SMP Sat Oct 17 05:06:47 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
  - OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output

Issue:
Recently, socket io report a security issue, we need upgrade socket.io version to 2.4.0 or later
https://exchange.xforce.ibmcloud.com/vulnerabilities/195255

**Comment by billchurch** [comment]
This is targeted for 0.4.0, you can check this out now in a840ec1

**Comment by billchurch** [comment]
fixed in [0.4.0 release](https://github.com/billchurch/webssh2/releases/tag/0.4.0)
