### ISSUE TITLE
How to connect to a server via a 2FA gateway?

### ISSUE THREAD

**Issue by Jiehong** [billchurch/webssh2#225]
I'm unable to connect to a server via a 2FA gateway with webssh2.

In particular, with ssh, I can do that:

```
ssh gu=gateway_username@username@target.host@gateway.host
```

This would lead to 3 prompts:

1. request my gateway_username password
2. request a 2FA token (by the gateway.host)
3. request my username password (by target.host)

Without the gateway, this would be a simple `ssh username@target.host`, but in this case, this is just possible.

I haven't been able to make this work with webssh2.

**Comment by billchurch** [comment]
It doesn't seem like 2fa is really your question, but how do you do use an ssh gateway host with WebSSH2. 

I don't have an answer for you, but might be able to help with more information. What is the ssh server that's operating at this gateway host? Not familiar with this syntax for ssh.

Feel free to re-open this issue with the response.
