### ISSUE TITLE
How to target 2 hosts on different hostname and port?

### ISSUE THREAD

**Issue by Jiehong** [billchurch/webssh2#226]
I have a local ssh server (a vagrant VM), so in config.json, I set "localhost" and port "2222" as the default ssh.

This works well when I go to http://localhost:2223/ssh/host/localhost (note: port changed to 2223, as vagrant uses port 2222)

Now, I want to connect to another host on port 22, but I can't.

If I go to http://localhost:2223/ssh/host/my.host.com, it tries to go to port 2222, which is wrong.

Using `http://localhost:2223/ssh/host/my.host.com:22` or `http://localhost:2223/ssh/host/my.host.com/22` does not work (a wild guess).

How can I do that?

Depending on the type of issue, please include the following information:

- Node and NPM Version
  - `node -v` -> v 12.9.0
  - `npm -v` -> 6.10.2

- Server OS Version / Distribution / Processor Architecture
  - Windows 10
  - 
- WebSSH2 release version
  - `grep version app/package.json` -> 0.3.0

**Comment by agent-squirrel** [comment]
You can pass GET parameters to the application like so:

`http://localhost:2223/ssh/host/my.host.com?port=22`

**Comment by Jiehong** [comment]
Thanks @agent-squirrel !
