### ISSUE TITLE
How to hide vetrical scrollbar ?

### ISSUE THREAD

**Issue by qstesiro** [billchurch/webssh2#227]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
  - `npm -v`
- Server OS Version / Distribution / Processor Architecture
  - `uname -a`
  - `cat /etc/os-release`
- WebSSH2 release version
  - `grep version app/package.json`
- OS and Version of SSH server connecting to
  - `uname -a`
  - `sshd -v`
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output

**Comment by billchurch** [comment]
Currently this seems to be a limitation of xterm.js. There's an open issue for it over there: 

https://github.com/xtermjs/xterm.js/issues/3074

Once it's supported here we can look at implementing something.

**Comment by billchurch** [comment]
closing for now as this depends on an upstream change which isn't yet roadmapped.
