### ISSUE TITLE
an error is throw new Error('Invalid listen argument: ' + h);

### ISSUE THREAD

**Issue by BeerLii** [billchurch/WebSSH2#23]
when I use npm start,it show this error: throw new Error('Invalid listen argument: ' + h); how can i solve

**Comment by choeyio** [comment]
Ensure that the IP and Port you're using are the correct types. Otherwise the listen call in index.js will fail.

server.listen({
  host: '0.0.0.0',
  port: 80
});

host must be of type string, and port must be of type integer.  I ran into this error b/c my port was being passed as a string.

**Comment by billchurch** [comment]
@choeyio is correct, ensure proper typing. Closing.
