### ISSUE TITLE
Refresh all the time when the user name or password is incorrect

### ISSUE THREAD

**Issue by just-zl** [billchurch/webssh2#231]
Hello, 
The browser is refreshing all the time when the user name or passwprd is incorrect. It bothered me for a long time, and I wanner known how to fix it. Thanks!

【node version: v12.16.1】
【npm version: 6.13.4】
【WebSSH2 release version: 0.3.1-pre-release-0.0】

**Comment by billchurch** [comment]
What browser and version are you using? The intended effect is that if the credentials are incorrect, it will redirect the user to /reauth (invalidate the current credentials) and request new credentials via basic auth.

It's been noted that Firefox will continue the cache these credentials, regardless of a 401... This doesn't seem right. Chrome does not exhibit this issue. See #196 for details on that.

Let me know if this clears things up, I'm going to close for now but feel free to re-open if you have more questions related to this.
