### ISSUE TITLE
Embedding in HTML page

### ISSUE THREAD

**Issue by SjVer** [billchurch/webssh2#232]
How would i go about embedding this into a normal HTML5 web page?

The structure of my web page folder so far:

```
mypage
   |_ index.html
   |_ main.css
   |_ node_modules
          |_ etc.
```

**Comment by billchurch** [comment]
It depends on what you're trying to accomplish. Essentially the important parts are inside ./app/client/public/

You will need webssh2.bundle.js as well as webssh2.css in the same folder as client.html or you'll need to provide the paths inside client.html to where those live.

The contents of client.html are the bare minimum required to get a session going, so you'll need everything inside that file to get up and running. 

You'll of course need the node server to be running somewhere and you'll need to forward the websocket requests to that node server...
