### ISSUE TITLE
Wireshark shows ssh packets from client to server as malformed

### ISSUE THREAD

**Issue by djmalc** [billchurch/webssh2#250]
Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
  - `npm -v`
- Server OS Version / Distribution / Processor Architecture
  - `uname -a`
  - `cat /etc/os-release`
- WebSSH2 release version
  - `grep version app/package.json`
- OS and Version of SSH server connecting to
  - `uname -a`
  - `sshd -v`
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output

**Comment by djmalc** [comment]
With npm v6.14.121 node v14.16.0, latest webssh2 cloned from github and running on Macbook Pro macOS 10.15.7. Only change is configuration to ssh to a test Debian server (e.g. ssh:host="192.168.0.65" user:name="test" user:password="testxyz") 
Running Wireshark on Macbook Pro with filter of ssh. In Chrome browse to http://localhost:2222/ssh/host/127.0.0.1 and terminal starts up correctly and works fine but when you do a Wireshark capture, packets with src=localhost dst=192.168.0.65 show up as Malformed Packet - after several seconds the info column description changes from "Malformed" to "Client:Encrypted Packet" but double-clicking to display detail shows that they are still in fact "Malformed Packet (Exception occurred)". 
Packets with src=192.168.0.65 dst=localhost show up as normal Server:encrypted packets.

If use command line ssh to connect to the same Debian server and run same Wireshark capture all Client packets are correctly formed and are not reported as being malformed.

**Comment by billchurch** [comment]
This looks like an issue in the upstream package mscdex/ssh2, i've [opened an issue there and tagged this issue](https://github.com/mscdex/ssh2/issues/1011).

It doesn't seem to cause any problems as far as I can tell, but it is curious. I've seen issues with wireshark dissectors in the past but will await comments from the upstream package maintainer.

**Comment by djmalc** [comment]
Thanks Bill -apologies for blaming the wrong person!

**Comment by billchurch** [comment]
from @mscdex:
> There is no problem with `ssh2`. The wireshark dissector just makes some bad assumptions. In this particular case it's assuming the entirety of an SSH identification exists in a single chunk, that's why you don't see the client identification ever get decoded (it just shows up as plain TCP data). The fix for the dissector would be to buffer (since TCP is a stream) until the terminating CR-LF is seen.
> 
> EDIT: I should note that when I tried it myself with the same node version (and `ssh2` master) the issue was present at the very beginning of the connection, not after the handshaking, but it's most likely the same type of issue.

Makes sense, closing this as well as an issue with the Wireshark dissector.
