### ISSUE TITLE
keyboard distribution changes in Chrome

### ISSUE THREAD

**Issue by majezt1c** [billchurch/webssh2#263]
When connecting via WebSSH2 to any host, my keyboard distribution changes to the American distro, which makes it a problem, since I use the Spanish one. The weirdest part of it is that this issue only happens when I'm using Chrome, while it works perfectly on other web browsers such as Firefox, Chromium or Opera. 

I was wondering if this could be fixed or it could be added a locale field in any config file.

Thanks in advance,

Andrés

**Comment by billchurch** [comment]
I will look into it. Is this on Windows or macOS and do you know which version of OS and chrome?

**Comment by billchurch** [comment]
Looks like it's an open issue with xterm.js: https://github.com/xtermjs/xterm.js/issues/3459

Will monitor it and update when resolved. There seems to be a workaround in there.

**Comment by majezt1c** [comment]
It is happening with Chrome v 94.0 and Ubuntu 20.04. Will have a look into that issue as well. Thank you, will appreciate any updates!

**Comment by majezt1c** [comment]
It has also been tested in macOS and win10, both with Chrome version 94.0 and seems to be working just fine, it keeps the Spanish keyboard distribution. Most likely to be a problem with Chrome when running in Ubuntu/Debian versions. 

I also did some testing on Chrome v88 with Linux Mint and it also worked the way it was intended, keeping the OS keyboard distro, so I'm thinking it is a problem with Ubuntu's Chrome 92.0+ versions and xtermjs, if this could help anyhow.

**Comment by n-lim-pyres** [comment]
> Looks like it's an open issue with xterm.js: [xtermjs/xterm.js#3459](https://github.com/xtermjs/xterm.js/issues/3459)
> 
> Will monitor it and update when resolved. There seems to be a workaround in there.

The issue is lower leven than xterm.js.  
It's related to how Chromium itself handles inputs on some Linux distros.

I've created an issue on the Chromium bug tracker more than one month ago, but it still hasn't been fixed:  
https://bugs.chromium.org/p/chromium/issues/detail?id=1245196&q=keyboard%20french&can=2

If you're affected by that problem, don't hesitate to star it so that they now it's a widespread problem.

**Comment by majezt1c** [comment]
Just wanted to let you know that last Chrome update (ver. 96.0) fixed this issue.

Thank you for your time!
