### ISSUE TITLE
ctrl+w closes the browser window in webssh2

### ISSUE THREAD

**Issue by premkumarrtech** [billchurch/webssh2#267]
Browser is getting closed when we press ctrl+w in webssh2 app

ctrl+w is assigned to search a text in nano editor in linux\ubuntu

Please help me on this

- Node and NPM Version
  - `node -v` v14.17.5
  - `npm -v` 6.14.14
- Server OS Version / Distribution / Processor Architecture
  - `cat /etc/os-release` 
    NAME="Ubuntu"
    VERSION="20.04.3 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04.3 LTS"
    VERSION_ID="20.04"
- WebSSH2 release version
  - `grep version app/package.json` 0.4.2
- OS and Version of SSH server connecting to
  - `sshd -v` OpenSSH_8.2p1 Ubuntu-4ubuntu0.3, OpenSSL 1.1.1f
- Browser Version and OS
  - chrome 95.0.4638.54
  - windows 10 - 64bit
- Any log or messages from the WebSSH2 output
  - none
- screenshot of nano editor
![image](https://user-images.githubusercontent.com/38245037/138851389-de4d20d8-2170-40bc-be82-ae6fe50a7120.png)

**Comment by billchurch** [comment]
Yeah, everything points to this being hard-wired for Windows and Linux versions (Mac uses command+W so not an issue there). There are some browser extensions which can help (though user has to install) 

- https://chrome.google.com/webstore/detail/better-ctrl-w/jfknaapblnppeflfamkegnnonlfgokhp?hl=en-US
- https://superuser.com/questions/569248/disable-hardwired-chrome-hot-key-ctrlw

And some OS level fixes:
- https://suraj.io/post/disable-ctrl-w/

Closing this as it seems not possible in the code we control.
