### ISSUE TITLE
Unable to load web terminal using localhost (WEBSOCKET SERVER DISCONNECTED)

### ISSUE THREAD

**Issue by Adithya1996** [billchurch/webssh2#273]
- Node and NPM Version
  - `node -v` : 16.13.2  
  - `npm -v` : 8.1.2
- Server OS Version / Distribution / Processor Architecture
  - `uname -a` : MINGW64_NT-10.0-19043 (Windows 10)
  - `cat /etc/os-release`
- WebSSH2 release version
  - `grep version app/package.json` :   "version": "0.4.4",
                                                             "release": "standard-version"
                                                             "standard-version": "^9.3.0",
- OS and Version of SSH server connecting to
  - `uname -a` : Same as server os
  - `sshd -v` :  OpenSSH_8.2p1, OpenSSL 1.1.1f  31 Mar 2020
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
- Any log or messages from the WebSSH2 output : Attaching the log file with debugs enabled.
[logs.txt](https://github.com/billchurch/webssh2/files/7941546/logs.txt)

I have followed the installation steps as mentioned in the README. Post that I installed openssh on my machine.

I have made the firewall changes to open port 22 but am still unable to login to localhost after adding the correct credentials for username and password.

Can someone please help me as to what I have done wrong in my setup?

**Comment by billchurch** [comment]
First off, thanks for filling out the issue template, helps a lot. 

Check the log, you'll see you're getting an authentication error, invalid username or password potentially? 

```

2022-01-26T12:01:21.901Z ssh2 Outbound: Sending USERAUTH_REQUEST (password)
2022-01-26T12:01:21.916Z ssh2 Inbound: Received USERAUTH_FAILURE (publickey,password,keyboard-interactive)
2022-01-26T12:01:21.916Z ssh2 Client: password auth failed
2022-01-26T12:01:21.916Z ssh2 Outbound: Sending USERAUTH_REQUEST (keyboard-interactive)
2022-01-26T12:01:21.931Z engine:socket writing a noop packet to polling for fast upgrade
2022-01-26T12:01:21.932Z engine:polling writing "6"
2022-01-26T12:01:21.933Z ssh2 Inbound: Received USERAUTH_FAILURE (publickey,password,keyboard-interactive)
2022-01-26T12:01:21.933Z ssh2 Client: keyboard-interactive auth failed
WebSSH2 [1m[31merror: Authentication failure[39m[22m user=[4m[1m[33mAdithya Raviraja[39m[22m[24m from=[4m[1m[33m127.0.0.1[39m[22m[24m

```

**Comment by billchurch** [comment]
Additionally I've done no testing with Windows so that's going to be uncharted territory for me. Id suggest looking at the ssh logs on the host to see what it's saying. I notice a space in your username, quite unusual for Linux but maybe something common for Windows SSH?

Maybe try your sAMAccountname or UPN instead?

**Comment by Adithya1996** [comment]
Thank you for your prompt reply, I have tried another way of setting up a webssh2 and would like your inputs if you wouldn't mind. I have spun up 2 ubuntu 20 virtual machines (let's call them vm1, vm2) in digitalOcean with ip1, ip2 as addresses. I have setup webssh2 in vm1 and want to open a web terminal of vm2. 

Using my physical machine (windows 10) I have i tried to fire the following url "http://<ip1>:2222/ssh/host/<ip2>" . But I seem to be hitting the same password related issue mentioned above. 

My question is which machine's credentials should I be passing as part of the pop up window? vm1, vm2 or the physical machine?

**Comment by billchurch** [comment]
Should be of vm1 or vm2

**Comment by billchurch** [comment]
And the proper url format is /ssh/host/<ipaddress>

Example, your web host running webssh2 is at 192.168.1.2 listening in port 2222 and the host you want to ssh into is 192.168.1.3:

```
http://192.168.1.2:2222/ssh/host/192.168.1.3
```

**Comment by Adithya1996** [comment]
Right, so I had tried this method. But I noticed a similar error of invalid user creds. But the log file shows "WebSSH2 error: Authentication failure user=root from=<physical_machine_ip>". Not sure why this ip is being picked when I running this scenario. Am I missing any config value changes? For now I have simple created config.json with the contents of config.json.sample

**Comment by Adithya1996** [comment]
Closing this, there were some ssh configs I had missed out prior to establishing a connection. Thank you for your time.

**Comment by adithya-raviraja** [comment]
hi @prateekagrawl,

I had faced this issue in ubuntu. So here I had updated the sshd config file (forgot the exact location) for it

I had added the following entries 

PermitRootLogin yes
PasswordAuthentication yes

After that, I restarted the service and it worked. Maybe you can try this out.

**Comment by prateekagrawl** [comment]
Okay. What do you pass in the username and password popup because I get authorized error.

**Comment by adithya-raviraja** [comment]
Have you tried the current user and password for the root user or any custom user in the env? If i remember correctly you can set the username and password in the webssh config to avoid the popup.

**Comment by prateekagrawl** [comment]
![16855550485401425506295216050152](https://github.com/billchurch/webssh2/assets/60268597/55dfb76c-7320-49da-a84b-56707a3d5f46)



I tried to change password in app/config.json as root and root but was giving me unauthorised error. Is this the correct location or is there any other location?

**Comment by adithya-raviraja** [comment]
Yes this is the config. Unsure what else you can do at this moment.
