### ISSUE TITLE
I want a serverless SSH terminal in the browser. Is it possible?

### ISSUE THREAD

**Issue by bitcoinmeetups** [billchurch/webssh2#280]
Hello,

I'm MB. A very nice and polite guy.

I want a completely serverless SSH terminal in the browser. Is it possible? I. e. nothing running in the Terminal in the backend on the user's side.

This (your) project is interesting. Would I be able to use it for above purpose or do you know someone else that has a serverless SSH terminal for the browser?

**Comment by billchurch** [comment]
You're looking for something like this: https://chromium.googlesource.com/apps/libapps/+/HEAD/nassh/

My project requires server-side code.
