### ISSUE TITLE
cannot ssh into linux host based on a private key 'key' and a certificate 'key-cert.pub'

### ISSUE THREAD

**Issue by bbthekings** [billchurch/webssh2#281]
Depending on the type of issue, please include the follwing information:
- WebSSH2 release version  -  latest

I cannot find the function call to ssh into a linux host based on a private key 'key' and a certificate 'key-cert.pub' where the certificate is signed by a certification authority which is configured on the host as 'TrustedUserCAKeys /etc/ssh/user-ca-pubkey.pem'. Is this implemented or do I need to implement it by myself? If not implemented, how would you recommend to approach it? thanks

**Comment by billchurch** [comment]
PKI support (x.509) isn't implemented here. 

Likely not possible until the ssh2 module supports this: https://github.com/mscdex/ssh2/issues/551

**Comment by bbthekings** [comment]
thanks for the update.
