### ISSUE TITLE
Request to update Docker Hub version from 0.4.0 to latest

### ISSUE THREAD

**Issue by Frooodle** [billchurch/webssh2#287]
Request to update Docker Hub version from 0.4.0 to latest
https://hub.docker.com/r/billchurch/webssh2/tags

**Comment by billchurch** [comment]
okay, i think i got it sorted with automation from github actions at this point. i published 0.4.5 and 0.4.6 retroactively, i also have an image built with every push to `main`, tagged as `main` which may be breaking, so beware when using the `main` tag.

`latest` should be safe.  

check it out on docker hub and see if that's what you're looking for.

**Comment by Frooodle** [comment]
Awesome! thanks
