### ISSUE TITLE
UTF8 error on refresh window after key down 'ñ'

### ISSUE THREAD

**Issue by bara666** [billchurch/webssh2#289]
Hi @billchurch,

I am trying to update the version and in the new version I find a couple of problems related to UTF-8. When I type a UTF-8 character from the keyboard the screen refresh throws weird encodings.
![image](https://user-images.githubusercontent.com/8573431/177155919-24245741-b5a7-4067-9959-bbb10ea57951.png)
but if I write on file text and show it on shell, there aren't problem
![image](https://user-images.githubusercontent.com/8573431/177156128-69839d7a-0928-45fc-aab7-010ff0a079f7.png)

And the 'ls' command doesn't detect UTF-8 correctly
![image](https://user-images.githubusercontent.com/8573431/177156522-0322a724-15ac-496b-890e-7b186d90cf42.png)

Depending on the type of issue, please include the follwing information:
- Node and NPM Version
  - `node -v`
     -  > v16.15.1
  - `npm -v`  -> 8.11.0
     -  > 8.11.0
- Server OS Version / Distribution / Processor Architecture
  - `uname -a` -> 
     -  > Linux pt-desa09u 5.13.0-51-generic # 58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
  - `cat /etc/os-release`
     - > NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

- WebSSH2 release version
  - `grep version app/package.json`
     - > "version": "0.4.6",
    "release": "standard-version"
    "standard-version": "^9.3.0",
- OS and Version of SSH server connecting to
  - `uname -a`
     -  > Linux pt-desa09u 5.13.0-51-generic # 58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022 
  - `sshd -v`
     - > OpenSSH_8.2p1 Ubuntu-4ubuntu0.5, OpenSSL 1.1.1f  31 Mar 2020
- Browser Version and OS
  - Information from brwoser's About... or a screenshot of the about screen.
  - 
![image](https://user-images.githubusercontent.com/8573431/177154903-57ccdbcd-19cf-4253-aa68-19e6b9b2427c.png)

- Any log or messages from the WebSSH2 output

**Comment by bara666** [comment]
I debug the function
![image](https://user-images.githubusercontent.com/8573431/177157802-b1eabeaf-dba5-4b66-a83e-abf249e5b5b3.png)

**Comment by billchurch** [comment]
Glad you figured it out! Also, thank you for such a detailed issue.
