### ISSUE TITLE
dockerhub only ARM images available

### ISSUE THREAD

**Issue by zwiy** [billchurch/webssh2#293]
The last image built for `amd64` is 0.4.0. Currently there are only `arm64` images available with newer tags.

Is it possible to build and push them for `amd64` too?

https://hub.docker.com/r/billchurch/webssh2/tags

Thanks!

**Comment by billchurch** [comment]
Yes, this is an oversight, will do in a bit.

**Comment by billchurch** [comment]
I think I got this worked out for 0.4.6 (latest) and main. Will document a bit more but should be usable now.
