### ISSUE TITLE
How to build production

### ISSUE THREAD

**Issue by L-sizhong** [billchurch/WebSSH2#31]
I want to use this in produtcion envirment, but it contains source file and any other file that no need to run. So, can you please tell me how to build production in envirment, just like Java Web build to .war or Java source build to .jar? Thanks

**Comment by billchurch** [comment]
This is a nodejs application, not a Java application, not sure how to help you turn it into a .war/.jar.

**Comment by L-sizhong** [comment]
Sorry, my English is poor, not express what I mean. Maybe you can tell me what file are necessary in runtime, so I can build them as a zip file.
