### ISSUE TITLE
[Bug]: Wrong cols and rows on connect

### ISSUE THREAD

**Issue by w-v** [billchurch/webssh2#315]
### What happened?

On connection, the rows and columns counts are not set
Resize works fine

### Node Version

`v19.0.0`

### NPM Version

`8.19.2`

### Server OS Version

```
Linux ajax 6.0.2-arch1-1 #t1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
```

### WebSSH2 release version

`0.5.0-pre-4`

### OS and Version of SSH server

```
Linux ajax 6.0.2-arch1-1 #t1 SMP PREEMPT_DYNAMIC Sat, 15 Oct 2022 14:00:49 +0000 x86_64 GNU/Linux
OpenSSH_9.1p1, OpenSSL 1.1.1q  5 Jul 2022
```

### Browser Version

`Chromium 106.0.5249.119 Arch Linux`

**Comment by billchurch** [comment]
fixed in #337
