### ISSUE TITLE
[Bug]: WebSSH2 error: Authentication failure user=root from=103.170.221.89

### ISSUE THREAD

**Issue by krishnashed** [billchurch/webssh2#320]
### What happened?

I'm not able to get a web terminal as mentioned in the repository, I enter the username and password created for a linux user, but still I get Authentication error. I tried it across multiple versions like main, current, latest and multiple deployments like test, production. But the issue still persists.

Steps I followed till now are
1. cloning the repository, cd app/
2. git checkout latest or git checkout latest, then npm install or npm install --production, The issue exists on all versions & install versions
3. Setting PermitRootLogin yes in /etc/ssh/sshd_config, refered stackoverflow 
4. creating users with password, using sudo useradd username -p password
5. Entering the exactly same username and password in website at url http://<server-ip>/ssh/host/<server-ip>, where <server-ip> is the public ip address of Instance where i have webssh2 running. 

But it doesn't work, It doesnt allow me to login and gives error such as 'WebSSH2 error: Authentication failure user=root from=103.170.221.89'

Please Help

### Node Version

v18.12.1

### NPM Version

8.19.2

### Server OS Version

Linux ip-172-31-0-236 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux PRETTY_NAME="Ubuntu 22.04.1 LTS"

### WebSSH2 release version

  "version": "0.4.6",     "release": "standard-version"     "standard-version": "^9.3.0"

### OS and Version of SSH server

OpenSSH_8.9p1 Ubuntu-3, OpenSSL 3.0.2 15 Mar 2022

### Browser Version

Google Chrome (WIndows) Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by zhangchaoxu** [comment]
I donot know how this issue happen, but reopen brower can fix this issue.
