### ISSUE TITLE
How to add support for ssh key algorithm ed25519

### ISSUE THREAD

**Issue by nareshblu** [billchurch/webssh2#324]

**Comment by billchurch** [comment]
It should work as long as you're using node 12.x+. You would add this to the algorithms section in config.json. Are you seeing something different?

**Comment by nareshblu** [comment]
> It should work as long as you're using node 12.x+. You would add this to the algorithms section in config.json. Are you seeing something different?

I am using node v4.9.1. I am not sure what should be the kex and cipher values I have to add in config.json.

**Comment by billchurch** [comment]
They would be the same as openssh conf. Whatever the settings are in your openssh conf 

Also, you just have Node v12 or above for this to work. If you're on Node v4, it will not.
