### ISSUE TITLE
【Excuse me?】How can I change my ssh pw at each ssh connection.

### ISSUE THREAD

**Issue by rvier** [billchurch/WebSSH2#34]
Firstly thank you for your convenient project .
But I have a problem: If I inputed wrong ssh pw in first connection I don't know how to correct it......

**Comment by rvier** [comment]
ok, clear cookies

**Comment by billchurch** [comment]
@rvier 

I plan on making a change shortly that will give you the option to switch from basic auth, to modal dialog. Also I'm investigating the possibility to re-prompt for credentials when using basic auth.

**Comment by j8la** [comment]
It will be a very good thing, your client is very great (the best web ssh client for me) but the authentication cache is painful.

**Comment by thiago-paz** [comment]
@billchurch 

Do you have any update on this issue?

by the way, I make @j8la words my own. Your **WebSSH2** project is really awesome.

But for now,  the "authentication by cookie" is being an impediment to using **WebSSH2** for production environment. 

Thanks for share it

**Comment by billchurch** [comment]
Based on the way I'm processing credentials from Basic Auth, I can't (yet) re-prompt for credentials. The way this was initially intended to work, the password would never be wrong (using SSO from another utility).

In any event, I'm planning to provide a different way to ask for credentials in the next major release.

**Comment by billchurch** [comment]
resolved, see issue #51
