### ISSUE TITLE
Changing terminal name in config.json for better usability 

### ISSUE THREAD

**Issue by Alex5434** [billchurch/webssh2#353]
**Is your feature request related to a problem? Please describe.**
The current terminal name is "xterm-color", it works fine but when i use commands like "htop" the mouse clicks and scrolls are disabled.

**Describe the solution you'd like**
By changing the terminal name to "xterm-256color" it  support for 256 colors enabled and also solves this mouse problem.

![image](https://github.com/billchurch/webssh2/assets/101403536/75e66023-a150-417e-b4ce-51db97640512)

**Comment by billchurch** [comment]
the GET parameter `sshterm=` can be used on the URL to set the term to whatever you want.

```
https://localhost:2222/host/192.168.1.1&sshTerm=xterm-color256
```

Should do what you want. Of course you can also edit the config.json or if you're using docker you can bind a local `config.json` to the space in the container where it expects it (just tested this with `0.4.6`)

```
docker run -it --rm --name webssh2 -p 2222:2222 --mount type=bind,source=./config.json,target=/usr/src/config.json -e DEBUG="webssh2*" billchurch/webssh2:latest
```

I'll consider making this the default in future versions though.
