### ISSUE TITLE
Waiting for terminal command to finish execute then run another

### ISSUE THREAD

**Issue by theunreal** [billchurch/WebSSH2#36]
First of all, amazing project!

I am using it to execute a series of events by simply clicking a button. the code I added is:

```
<div id="runCommand"><a class="toggleLog" href="javascript:void(0);"
        onclick="runCommand();">Write command</a></div>
		
		<script type="text/javascript">
		function runCommand() {
			var filename = 'bigFile.txt';
                       console.log(term);
			term.send(`copy tftp://my-ip/tmp/${filename} dir:\n`);
                          console.log(term);
			term.send('\n');
			term.send('dir\n');
		}
		</script>
```

The problem is that dir is not executing, because the command before takes time to copy the file.

Is there any solution or way to check that the terminal is in writeable state? I tried to check for the `writable` flag of the term object but it is true.

Thanks!

**Comment by billchurch** [comment]
Well, what you're doing is going to be difficult in the way this app works since this is meant to be interactive, not programmatic. However, in the time being you can put all your commands on a single like and separate them with a semi-colon, and that should have the effect you want.

How would you do it if you were using an ssh cli client?

**Comment by theunreal** [comment]
@billchurch Thanks for your reply,
I can't do that with ssh cli client, I need to wait until the copy command is finishing and only then I'm able to execute another command. Currently I am trying to automate a bunch of executions.

Anyway - I think I have an idea, Is there any way to execute a command (term.send) when the terminal includes "OK" in the output?

**Comment by theunreal** [comment]
@billchurch I tried to seperate commandsd with semi colon, but they execute only when I type \n.

I never done that with ssh client, I am trying to automate this proccess with this library.

**Comment by billchurch** [comment]
Yes, you would need the \n, but the shell will execute one command after the other when using semi-colons. See this excerpt from Unix powertools: https://docstore.mik.ua/orelly/unix3/upt/ch28_16.htm

Should do what you want.

**Comment by theunreal** [comment]
Thanks @billchurch, it is indeed does the trick.
