### ISSUE TITLE
Webssh2 doesn't support ssh config files

### ISSUE THREAD

**Issue by 0xkyles** [billchurch/webssh2#362]
Webssh2 doesn't support ssh config files ? is there a way to implement this?

**Comment by billchurch** [comment]
I assume you're talking about [ssh_config](https://linux.die.net/man/5/ssh_config) style?

How would you want to see this implemented?
What functionality from there would you want?

We must ensure feature parity exists with the [upstream ssh2 module](https://github.com/mscdex/ssh2).
