### ISSUE TITLE
How should I use a proxy to connect to ssh（我应该怎么使用代理连接ssh）

### ISSUE THREAD

**Issue by yangzf01** [billchurch/webssh2#363]
I plan to use a web page to implement proxy link ssh, like winscp. As shown below
（我打算用网页实现代理链接ssh，像winscp。如下图）

![20240516160828](https://github.com/billchurch/webssh2/assets/169895130/b02aa727-2685-4693-a1fa-c1be5d35fda6)

![20240516160700](https://github.com/billchurch/webssh2/assets/169895130/f4f6847c-c950-485c-9754-9dded075ff94)

**Comment by billchurch** [comment]
You don't, you'd need to add the functionality if you want something like that. Kind of out of scope for what I intended.
