### ISSUE TITLE
"lastest" tag on docker hub is broken

### ISSUE THREAD

**Issue by israel-tsadok-silk** [billchurch/webssh2#369]
Apologies if this is not the right place to report this. On docker hub, the "latest" tag now only has an image with linux/arm64 architecture.
Since "latest" is the default tag when pulling docker images, this causes it to fail on amd64 platforms.
Error message:
```
WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
```
And also
```
image with reference docker.io/billchurch/webssh2:latest was found but does not match the specified platform: wanted linux/amd64, actual: linux/arm64
```

**Comment by billchurch** [comment]
Thanks for noticing that! It was a mistake due to a testing version I was publishing... It's been corrected!

https://hub.docker.com/layers/billchurch/webssh2/latest/images/sha256-7857392a6d574f9e4a826326144a371566139232c0b400377aaa1d353d982fe0?context=explore
