### ISSUE TITLE
https

### ISSUE THREAD

**Issue by itwars** [billchurch/WebSSH2#37]
Hi,

Really a great tool. Anyway is there a change to make it with https?

BR.

**Comment by billchurch** [comment]
It's meant to be used behind some sort of proxy which would handle the tls, however you can modify the code in app.js to utilize https instead of http, you'll need a cert and key of course. Will take a pull request for anyone that wants to make this an optional feature. I will put it on the todo list until them.

**Comment by tgotthard** [comment]
Hi,

do you have a "app.js" file that works with https?

**Comment by itwars** [comment]
Hi,
I use Traefik in front of webssh2, Traefik take care of https, as well as Letsencrypt cert!

**Comment by tgotthard** [comment]
Hi,

do you have a tutorial for your solution?

**Comment by itwars** [comment]
Yes I wrote one a while ago, but in French, anyway, using Google Translate it could make the job : https://www.it-wars.com/posts/performance/docker-traefik-letsencrypt/

Ask me if you need any extra details.

**Comment by ChrisHanuta** [comment]
I'm using an apache reverse HTTPS proxy with Letsencrypt cert. It works fine, and there are also several other applications on the proxy that I manage via webssh2. I do not use encryption on the local network.

**Comment by Utopiah** [comment]
Here is a quick example. The path could be replaced by a configuration option.

```javascript
//var server = require('http').Server(app)
var fs = require('fs')
const options = {
    cert: fs.readFileSync('/full/path/certificates/fullchain.pem'),
    key: fs.readFileSync('/full/path/certificates/privkey.pem')
};
var server = require('https').Server(options, app)
```
