### ISSUE TITLE
[Bug]: Not installed

### ISSUE THREAD

**Issue by KupueIIIKo** [billchurch/webssh2#377]
### What happened?

![image](https://github.com/user-attachments/assets/7cdbb34c-cfde-41e5-80d7-31cfac2d333b)

I just erased the spaces and retyped and it worked! Double check! Maybe it was just me

### Node Version

20.18.0

### NPM Version

10.8.2

### Server OS Version

Ubuntu

### WebSSH2 release version

last

**Comment by billchurch** [comment]
I think you have something wrong with your system, I'm not able to recreate this or #378 you posted. it looks like maybe you have some cr/lf issues or something along those lines.
