### ISSUE TITLE
[Bug]: BAD SCRIPT

### ISSUE THREAD

**Issue by KupueIIIKo** [billchurch/webssh2#378]
### What happened?

A bug happened!
![image](https://github.com/user-attachments/assets/2da8d894-b023-440f-9362-6300277bfd9b)

### Node Version

20.18.0

### NPM Version

10.8.2

### Server OS Version

Ubuntu

### WebSSH2 release version

last

**Comment by billchurch** [comment]
It looks like you're running direct from `main`, however I'm not able to re-produce your error, Additionally running directly from the `main` branch is not advised as that is considered unstable. You're better off pulling from a release. 

https://github.com/billchurch/webssh2/tree/0.4.6

Is the most recent stable release.
