### ISSUE TITLE
parsing messages from the terminal

### ISSUE THREAD

**Issue by theunreal** [billchurch/WebSSH2#38]
Hi,
Is there any event to watch for terminal outputs?

**For example:** executing "ls" and then parse the output string of all the dirs / files

**Comment by billchurch** [comment]
The question is, do you want this to happen from a client perspective (browser) or from a server-side (node) perspective? 

From a client perspective, all events from the server will be in "socket.on" events. The one specifically for SSH data will be "socket.on('data').

https://github.com/billchurch/WebSSH2/blob/88ad8210f37780b3afbcebd15b1d2ddab366adfe/src/js/client.js#L118

In this event you can write whatever javascript you want to do something with _data_

From a server (node) perspective, all events from the ssh server are in "stream.on('data')"

https://github.com/billchurch/WebSSH2/blob/88ad8210f37780b3afbcebd15b1d2ddab366adfe/socket.js#L86

**Comment by billchurch** [comment]
closing question
