### ISSUE TITLE
Can't retry login

### ISSUE THREAD

**Issue by dezechristophe** [billchurch/WebSSH2#4]
on first try, I did give login informations.
now, each time i refresh http://localhost:2222/ssh/host/127.0.0.1, I get : 

` npm start

> WebSSH2@0.0.2 start /home/christophe/tmp/WebSSH2
> node index
/home/christophe/tmp/WebSSH2/node_modules/ssh2/lib/client.js:209
    throw new Error('Invalid username');
    ^
Error: Invalid username
    at Client.connect (/home/christophe/tmp/WebSSH2/node_modules/ssh2/lib/client.js:209:11)
    at Namespace.<anonymous> (/home/christophe/tmp/WebSSH2/index.js:105:8)
    at emitOne (events.js:96:13)
    at Namespace.emit (events.js:188:7)
    at Namespace.emit (/home/christophe/tmp/WebSSH2/node_modules/socket.io/lib/namespace.js:209:10)
    at /home/christophe/tmp/WebSSH2/node_modules/socket.io/lib/namespace.js:177:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
npm ERR! Linux 4.4.0-57-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! WebSSH2@0.0.2 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WebSSH2@0.0.2 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the WebSSH2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs WebSSH2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls WebSSH2
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/christophe/tmp/WebSSH2/npm-debug.log
`

**Comment by billchurch** [comment]
Just to verify, are you **NOT** entering a username or password when this error is produced, correct?

While there's not a routine to prompt for credentials again (something I can look into) it should not crash as it did if a username is not entered. I'll fix that.
