### ISSUE TITLE
Option for per request authentication

### ISSUE THREAD

**Issue by AODtorusan** [billchurch/WebSSH2#51]
Would it be possible to add an option to re-request the authentication each time you do a new request for an SSH session ?

We're using webssh on a jumphost server, but most target devices use different credentials. This means that almost every time we need to flush the browser authentication cache when we want to connect to a device, which is cumbersome.

**Comment by NetFunctional** [comment]
+1 - same use case, same issue.

**Comment by billchurch** [comment]
I love it. It’s in the queue.

**Comment by spamru** [comment]
I did a small workaround for that. However, you have to patch few files...

**Comment by richard-scott** [comment]
@vbeskrovny - Would you be able to share your workaround?

**Comment by vbeskrovny** [comment]
Sure, the link is under my profile or here: https://github.com/vbeskrovny/WebSSH2-session

**Comment by billchurch** [comment]
@vbeskrovny I'll take a look at this when I have a moment and try to integrate it if that's ok.

**Comment by vbeskrovny** [comment]
Cool, thanks. By the way I wanted to add custom calls to the onDisconnect events, to add some nice prompts and fancy UI, but the "bundle.js" has no source... :(

**Comment by vvalchev** [comment]
The provided patch, will add a /logout URL, which will re-request the authentication and then redirect you back to the referrer (e.g like http://localhost:2222/ssh/host/myhost.com).

It also adds a menu entry "Switch User" that opens /logout and forces re-authentication.

[logout-diff.txt](https://github.com/billchurch/WebSSH2/files/2218745/logout-diff.txt)

**Comment by billchurch** [comment]
@richard-scott and @AODtorusan I've merged this into `master` can you see if this now fits your use case or do you feel we need to expand it to cover your use case?

**Comment by billchurch** [comment]
Here's what the screen looks like:
![image](https://user-images.githubusercontent.com/1668075/43400846-c5e87720-93dc-11e8-94a7-551e97dbcb5e.png)

And the resulting prompt (I've been working on the styling to fit current style and methods)
![image](https://user-images.githubusercontent.com/1668075/43400905-ec07030e-93dc-11e8-9a1a-b5498ba43e79.png)

Option added to `config.json` as `options.allowreauth` to toggle this feature
