### ISSUE TITLE
Regarding integration of WebSSH2 in to my project

### ISSUE THREAD

**Issue by jaypadath** [billchurch/WebSSH2#56]
When opening an issue, please include the follwing information:
Node Version : v8.9.4
Server OS Version 
WebSSH2 release version : 0.2.3
OS and Version of SSH server connecting to 
Browser Version and OS : Firefox 58.0.2 (64-bit) 

Hi, is it possible to use WebSSH2 directly in to one of my project ? Front end is angular js and node js packaging is used to connect to remote host. My requirement is to create a new page with a terminal embedded in it and I should be able to ssh to host with specific port.

I installed WebSSH2 in my Ubuntu 16.04. From browser, while typing "http://localhost:2222/ssh/host/host_name", I am able to reach to ssh port. So is it possible to embed in a web page rather than invoking separately.

Thanks in advance, Jay.

**Comment by billchurch** [comment]
I never really intended this project to work inside of another application. While it's certainly possible, I do utilize Express sessions to pass variables and such so it's reliant on that. It would definitely work but you'd need to work out that bit.
