### ISSUE TITLE
How to add paramters for ssh command

### ISSUE THREAD

**Issue by tranxuanhao2001** [billchurch/WebSSH2#57]
Hi sir,

Plz help me. I want to add some parameters to ssh command

For example: ssh **-tt** user@127.0.0.1 -p 22

**Comment by billchurch** [comment]
to specify the port, you can use the uri variable `?port=22`

for `-t` (Force pseudo-tty allocation) you add a "pty" option after this line:

https://github.com/billchurch/WebSSH2/blob/88f050bbcf45be7ccc3054495cf01cad01640dbc/server/socket.js#L45

See docs at https://github.com/mscdex/ssh2 for exec/shell pty for more details (excerpt here).

> exec(< string >command[, < object >options], < function >callback) - boolean - Executes command on the server. Returns false if you should wait for the continue event before sending any more traffic. callback has 2 parameters: < Error >err, < Channel >stream. Valid options properties are:
> 
> env - object - An environment to use for the execution of the command.
> 
> pty - mixed - Set to true to allocate a pseudo-tty with defaults, or an object containing specific pseudo-tty settings (see 'Pseudo-TTY settings'). Setting up a pseudo-tty can be useful when working with remote processes that expect input from an actual terminal (e.g. sudo's password prompt).
> 
> x11 - mixed - Set to true to use defaults below, set to a number to specify a specific screen number, or an object with the following valid properties:
> 
> single - boolean - Allow just a single connection? Default: false
> 
> screen - number - Screen number to use Default: 0
> 
> shell([[< mixed >window,] < object >options]< function >callback) - boolean - Starts an interactive shell session on the server, with an optional window object containing pseudo-tty settings (see 'Pseudo-TTY settings'). If window === false, then no pseudo-tty is allocated. options supports the x11 and env options as described in exec(). callback has 2 parameters: < Error >err, < Channel >stream. Returns false if you should wait for the continue event before sending any more traffic.
