### ISSUE TITLE
google chrome nothing？

### ISSUE THREAD

**Issue by hktalent** [billchurch/WebSSH2#6]
google chrome
nothing....thank you
![wechatimg3](https://cloud.githubusercontent.com/assets/18223385/22850789/f9f80b02-f04a-11e6-89e7-4de2d42ec5f0.jpeg)
GET http://localhost:2222/src/xterm.css 
GET http://localhost:2222/src/xterm.js 
GET http://localhost:2222/addons/fit/fit.js 
Uncaught ReferenceError: Terminal is not defined

safari:
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (xterm.css, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (xterm.js, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fit.js, line 0)
[Error] ReferenceError: Can't find variable: Terminal
	全局代码 (client.js:2)

origin	https://github.com/billchurch/WebSSH2.git (fetch)
origin	https://github.com/billchurch/WebSSH2.git (push)

 npm install -g ssh2 socket.io term.js express

**Comment by hktalent** [comment]
please run:
git status
git push file
haha。。。。。。。
thank you

**Comment by hktalent** [comment]
QQ1160:WebSSH2 xiatian$ pwd
/Users/xiatian/safe/node/WebSSH2
QQ1160:WebSSH2 xiatian$ find . -name xterm.css xterm.js fit.js
find: xterm.js: unknown primary or operator
QQ1160:WebSSH2 xiatian$ find . -name xterm.css
QQ1160:WebSSH2 xiatian$ find . -name xterm.js
QQ1160:WebSSH2 xiatian$ find . -name fit.js
QQ1160:WebSSH2 xiatian$

**Comment by hktalent** [comment]
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/exec-test
  remotes/origin/master

**Comment by billchurch** [comment]
I'm not sure what's going on with your installation. I just setup a fresh Ubuntu system, did a "git clone https://github.com/billchurch/WebSSH2 and it's cloning just fine? Proving from my development system:

![image](https://cloud.githubusercontent.com/assets/1668075/22857954/8fac5c42-f07e-11e6-8d72-7ce17cdcea07.png)

![image](https://cloud.githubusercontent.com/assets/1668075/22858029/a52c4cc4-f080-11e6-9ccc-cc112e803087.png)

I think your problem might be that you're doing  `npm install -g ssh2 socket.io term.js express` (global) when the instructions specifically state `npm install` (installing all required modules AND their specific versions defined in the package.json). `term.js` isn't even the right module, it's `xterm` and it's v2.2.3...

If you want to do it all a different way, you're on your own. This is working as designed if you follow the instructions.

Closed, problem with @hktalent 's environment.

**Comment by hktalent** [comment]
1、do
npm install
2、run
node index.jsp
3、error in web
SSH CONNECTION CLOSE - Error: Handshake failed: no matching client->server cipherError: Handshake failed: no matching client->server cipherError: read ECONNRESET CREDENTIALS
