### ISSUE TITLE
npm start is not working

### ISSUE THREAD

**Issue by masavanu** [billchurch/WebSSH2#64]
Hi billchurch,
   As you suggested I used your repository. Here are the steps I did:-

1. git clone https://github.com/billchurch/WebSSH2
2. npm install --production
3. npm start.

When I executed npm start it throws me following error:-

root@ubuntu:/home/ubuntu/WebSSH2# npm start

> webssh2@0.2.3 start /home/ubuntu/WebSSH2
> node index.js

WebSSH2 service reading config from: /home/ubuntu/WebSSH2/config.json
/home/ubuntu/WebSSH2/node_modules/read-config/lib/load/merge-configs.js:7
    return merge({}, ...configs, (a, b) => {
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/WebSSH2/node_modules/read-config/lib/load/merge-parents.js:3:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! webssh2@0.2.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webssh2@0.2.3 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webssh2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webssh2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webssh2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/WebSSH2/root@ubuntu:/home/ubuntu/WebSSH2# npm start

> webssh2@0.2.3 start /home/ubuntu/WebSSH2
> node index.js

WebSSH2 service reading config from: /home/ubuntu/WebSSH2/config.json
/home/ubuntu/WebSSH2/node_modules/read-config/lib/load/merge-configs.js:7
    return merge({}, ...configs, (a, b) => {
                     ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/WebSSH2/node_modules/read-config/lib/load/merge-parents.js:3:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.4.0-109-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! webssh2@0.2.3 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webssh2@0.2.3 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webssh2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webssh2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webssh2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/WebSSH2/npm-debug.log

Content from npm-debug.log:-
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle webssh2@0.2.3~prestart: webssh2@0.2.3
6 silly lifecycle webssh2@0.2.3~prestart: no script for prestart, continuing
7 info lifecycle webssh2@0.2.3~start: webssh2@0.2.3
8 verbose lifecycle webssh2@0.2.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle webssh2@0.2.3~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/ubuntu/WebSSH2/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle webssh2@0.2.3~start: CWD: /home/ubuntu/WebSSH2
11 silly lifecycle webssh2@0.2.3~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle webssh2@0.2.3~start: Returned: code: 1  signal: null
13 info lifecycle webssh2@0.2.3~start: Failed to exec start script
14 verbose stack Error: webssh2@0.2.3 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid webssh2@0.2.3
16 verbose cwd /home/ubuntu/WebSSH2
17 error Linux 4.4.0-109-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error webssh2@0.2.3 start: `node index.js`
22 error Exit status 1
23 error Failed at the webssh2@0.2.3 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the webssh2 package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs webssh2
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls webssh2
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any Idea? Why it is failing npm start

**Comment by billchurch** [comment]
You're running Node v4.x, read-config@2 uses v6 syntax so it will fail.

Run this if you're running Node v4:

`npm install read-config@1 --save
`
That should solve it.

**Comment by masavanu** [comment]
Hi,

Should I need to directly run this command?
How to check Weather Node Version?

**Comment by masavanu** [comment]
I will execute below commands and let you know the result:--
1. npm install read-config@1 --save
2. npm start

**Comment by billchurch** [comment]
Not sure what version of node will be installed on your system, you'd probably want to visit the Ubuntu forums to resolve that bit.

**Comment by billchurch** [comment]
Closing for now, if it still doesn't work let me know.

**Comment by masavanu** [comment]
I was using node version 4 here is the command output:-
ubuntu@ubuntu:~/WebSSH2$ node -v
v4.2.6

I executed 
1. npm install read-config@1 --save
2. npm start

When I executed npm start now it throws me below error:-

/home/ubuntu/WebSSH2/node_modules/ssh2-streams/lib/constants.js:210
var KEX_BUF = Buffer.from(DEFAULT_KEX.join(','), 'ascii');
                     ^

TypeError: ascii is not a function
    at Function.from (native)
    at Function.from (native)
    at Object.<anonymous> (/home/ubuntu/WebSSH2/node_modules/ssh2-streams/lib/constants.js:210:22)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/WebSSH2/node_modules/ssh2-streams/lib/utils.js:6:22)

**Comment by masavanu** [comment]
I resolved the above issue by upgrading node to v4.5.0.
Now, WebSSH2 is running and able to connect to host. Thanks for your time

**Comment by masavanu** [comment]
When I enter URL to connect to host it asks the authentication for the server were I started npm. It does not ask authentication for host were I am trying to connect.

Ex:- If I enter url-- http://10.11.100.88:2222/ssh/host/10.11.100.166
     It asks the authentication only for 88 server were I ran npm not for 166.

How it connect to 166 without credentials? 
Can you explain?

**Comment by billchurch** [comment]
The credentials it is requesting when you first connect are actually for the SSH server you ultimately want to connect to. In your case that's 10.11.100.166, those are the credentials that the HTTP BASIC auth is asking for. Whatever you give it there, it sends to the SSH server. There is no "local" authentication (i.e. 10.11.100.88, there's no auth happening for that server).

**Comment by masavanu** [comment]
https://user-images.githubusercontent.com/33349700/39921385-51b617be-5538-11e8-98df-82cc8af6aa62.png


If you see above link it says 10.11.100.88 is requesting for username and password

**Comment by billchurch** [comment]
This is due to the browser caching the credentials. This is a feature request that I've not gotten around to since the way I'm using it with a BIG-IP proxy, it sends new credentials with new requests so it's a little out of scope with what I'm working on. If you open an incognito browser session and try it, it should work.
