### ISSUE TITLE
Is there a way to turn off the cookies for basic auth?

### ISSUE THREAD

**Issue by cwolfinger** [billchurch/WebSSH2#75]
The software is awesome but the inability to change users or passwords limits the use-fullness.

**Comment by vidcentum** [comment]
Use Firefox. Closing the browser clears the sessions and it asks for user relogin (HTTP Basic Auth).

**Comment by Strubbl** [comment]
@vidcentum it would be nice to clear session without restarting the browser

**Comment by billchurch** [comment]
see solution in #85
