### ISSUE TITLE
Keeping session

### ISSUE THREAD

**Issue by michael-thayer** [billchurch/webssh2#76]
node-v8.11.3-linux-x64
Ubuntu 18.04 amd64
webssh2@0.2.1
OpenSSH_7.6p1 Ubuntu-4, OpenSSL 1.0.2n  7 Dec 2017
Firefox for Ubuntu 60.0.2 (64-bit)

This is a question first (should I have asked that elsewhere?), not yet an issue.  I was wondering whether there is some way to make sessions in WebSSH2 persistent over a loss of internet connection.  Hope that is clear.
Thanks!

**Comment by billchurch** [comment]
I like the idea. There would need to be some more session management. At this point the app is intentionally dumb, so we would need to build that out.

**Comment by hktalent** [comment]
@michael-thayer 
```
# in your system
apt install tmux
man tmux
```

**Comment by ZackMattor** [comment]
@billchurch we need the ability to authenticate the SSH session from a backend service and then use some kind of session token passed to the frontend to establish the connection. I think this may cover the use-case outlined here (persistent connection with the ability to bind to it with a token)

Would you entertain accepting a PR with this addition? I haven't looked too deep into what it would take to implement - but I think that would cover what we need.

**Comment by billchurch** [comment]
Always into any PRs that add functionality. It seems like it might be a big undertaking but happy to help where I can.

**Comment by ZackMattor** [comment]
I don't think it would be a huge lift and it would be very cool if we could implement it into the official repo here and contribute back vs us just forking it. Current thinking is that we could just add a new route `start_session` that would create the SSH link to the router and return back a session ID that the frontend implementor would be able to use to establish the web-socket link back to the SSH session. This would allow what @michael-thayer first expressed interest for and what we need - which is establishing the first connection from a 3rd party so credentials never reach the client application at all.

We're planning on leaving the ssh/host/:host route for backwards compatibility but it might be cool to deprecate that in favor of always using the SSH sessions mechanism. But that can be a different discussion :)

What do you think about modernizing the codebase a bit to support node v10+ and bring in some more modern JS syntax such as the fat-arrow syntax and await / async for promises. Node 6 is EOL.

**Comment by billchurch** [comment]
I’m good with all of this. 10+ is preferred, v6 compatibility was for a previous project that’s now been forked off. Let’s do it.

**Comment by billchurch** [comment]
So. First things first, probably need to update the existing code base? Does that make sense? Should start a branch for that. 

It also might make sense to fork off the client into its own repo...
