### ISSUE TITLE
Not compatible with your operating system or architecture: fsevents@1.2.4

### ISSUE THREAD

**Issue by Echirivella** [billchurch/WebSSH2#78]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm ERR! Linux 4.4.0-124-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/data/appl/WebSSH2/npm-debug.log

**Comment by billchurch** [comment]
Try this instead:

  npm install --production

That module, and a few others, are not required unless you’re doing development. What OS architecture are you using?

**Comment by Echirivella** [comment]
Linux 4.4.0-124-generic #148-Ubuntu SMP Wed May 2 13:00:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux. 

npm install --production
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

Thanks.

**Comment by Echirivella** [comment]
npm start

> webssh2@0.2.3 start /media/data/appl/WebSSH2
> node index.js

sh: 1: node: not found

npm ERR! Linux 4.4.0-124-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! webssh2@0.2.3 start: `node index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the webssh2@0.2.3 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webssh2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webssh2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webssh2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/data/appl/WebSSH2/npm-debug.log

**Comment by billchurch** [comment]
Well that’s wacky. I’ve been testing mostly with node 6+ now. Been traveling today, let me see what if can find out later on today or tomorrow. Otherwise if installing node 6 on a test system is an option, I’d try that.

**Comment by Merak1** [comment]
Having the same problem, waiting if there is a resolution

**Comment by TomSaw** [comment]
Same for me.. Just switched to ubuntu 18... now i've got this, when trying to 
npm install bootstrap@4.x.x

**Comment by billchurch** [comment]
Try branch 'package-upgrade-test' and see if this resolves your issues.

**Comment by rjha72** [comment]
How do u try this package-upgrade-test??

**Comment by billchurch** [comment]
Download this branch: https://github.com/billchurch/WebSSH2/tree/package-upgrade-test

Really all you need is the `package.json` from this build.

**Comment by avisdawn** [comment]
Is there any workaround the error? I am getting the same issue when I execute the command "npm i webpack --save-dev"

**Comment by pedped** [comment]
I have the same problem too

**Comment by vvalchev** [comment]
In the next examples, instead of installing different versions of node, I'm running node in docker. I'm also using the `master` from today.

I ran the following commands and they were successful:
```
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:8.11 npm install --production
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:6.14 npm install --production
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app appsvc/node:4.8.4_1710252240 npm install --production
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app appsvc/node:4.4.7_1710252240 npm install --production
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:8.11-alpine npm install --production
```

In all examples above, I'm running with `--production` flag, as well I'm cleaning up the node_modules folder.

In the following tests, install generated warning but application started successfully.
```
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:8.11-alpine sh -c 'npm install && npm start'
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:8.11 sh -c 'npm install && npm start'
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:6.14-alpine sh -c 'npm install && npm start'
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app node:6.14 sh -c 'npm install && npm start'
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app iron/node:5.10.1-dev sh -c 'npm install && npm start'
```
The warning:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
```

With the following test:
```
rm -rf node_modules && docker run -it --rm -v `pwd`:/app -w /app iron/node:4.2.6-dev sh -c 'npm install && npm start'
```
Installation succeeded with the warning above, but starting failed with:
```
WebSSH2 service reading config from: /app/config.json
/app/node_modules/read-config/lib/load/merge-configs.js:7
    return merge({}, ...configs, (a, b) => {
```

So I can suggest:
* Read the message - warnings are ok, it's just a warning.
* If you are not developer, use `npm install --production`
* Use node 6+!! Consider upgrading your node version - 8.11 is way faster than 6.14
* If you are developer, try installing a C compiler - I believe that fsevents get's compiled if not found for your OS/CPU.

**Comment by billchurch** [comment]
@vvalchev, so just to confirm this is working for you with node 6+? And you're right, as the instructions state unless you're developing always use `npm install --production`

As far as fsevents, it's only needed for webpack and development. Not a requirement to run this on a server, if you're wanting to modify the source javascript/html or css do this on a developer workstation and not in docker.

@vvalchev the Dockerfile was a contribution, I don't maintain it. Is there anything in there that needs to be updated that you can tell or is this just a case of instructions not being followed? Is there a way I can make this more clear for others?

**Comment by vvalchev** [comment]
@billchurch The above was just a series of tests, to find where the problem is and to resolve this issue and help people here. But yes - the conclusions are that project runs ok with node 6+.

Dockerfile is ok, no need to do any changes.

It might be good if you can create a docker-hub account. Then setup auto-build for WebSSH2:
https://hub.docker.com/add/automated-build/<username>/github/orgs/

It will periodically check for changes on the specified branch and will trigger a docker build. It's a very easy way to distribute it.

Btw the npm repository contains very old version of webssh2. Do you plan any updates there?

**Comment by Gujjar95** [comment]
I am also getting this error 
`npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN @abhishekgarg727/react-native-otp-inputs@0.5.0 requires a peer of react-native@^0.53.0 but none was installed.
npm WARN eslint-plugin-react-native@3.2.1 requires a peer of eslint@^3.17.0 || ^4.0.0 but none was installed.
`

**Comment by manjujidagi** [comment]
I am also getting this error
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

**Comment by ankitAMD** [comment]
root@17af31fa9983:~/people-counter/webservice/ui# npm install
intel-facial-recognition-demo@0.1.0 /root/people-counter/webservice/ui
├─┬ css-loader@0.27.3
│ ├─┬ postcss-modules-extract-imports@1.1.0
│ │ └─┬ postcss@6.0.23 
│ │   ├─┬ chalk@2.4.1 
│ │   │ └─┬ ansi-styles@3.2.1 
│ │   │   └── color-convert@1.9.3 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@5.5.0 
│ │     └── has-flag@3.0.0 
│ ├─┬ postcss-modules-local-by-default@1.2.0
│ │ └─┬ postcss@6.0.23 
│ │   ├─┬ chalk@2.4.1 
│ │   │ └─┬ ansi-styles@3.2.1 
│ │   │   └── color-convert@1.9.3 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@5.5.0 
│ │     └── has-flag@3.0.0 
│ ├─┬ postcss-modules-scope@1.1.0
│ │ └─┬ postcss@6.0.23 
│ │   ├─┬ chalk@2.4.1 
│ │   │ └─┬ ansi-styles@3.2.1 
│ │   │   └── color-convert@1.9.3 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@5.5.0 
│ │     └── has-flag@3.0.0 
│ └─┬ postcss-modules-values@1.3.0
│   └─┬ postcss@6.0.23 
│     ├─┬ chalk@2.4.1 
│     │ └─┬ ansi-styles@3.2.1 
│     │   └── color-convert@1.9.3 
│     ├── source-map@0.6.1 
│     └─┬ supports-color@5.5.0 
│       └── has-flag@3.0.0 
├─┬ extract-text-webpack-plugin@2.1.2
│ └─┬ webpack-sources@1.2.0
│   └── source-map@0.6.1 
├─┬ html-loader@0.4.5
│ └─┬ html-minifier@3.5.20
│   ├─┬ clean-css@4.2.1
│   │ └── source-map@0.6.1 
│   └─┬ uglify-js@3.4.8
│     └── source-map@0.6.1 
├─┬ jest@20.0.4
│ └─┬ jest-cli@20.0.4
│   ├─┬ istanbul-api@1.3.6
│   │ └─┬ istanbul-lib-instrument@2.3.2
│   │   └─┬ @babel/template@7.0.0-beta.51
│   │     └─┬ @babel/code-frame@7.0.0-beta.51
│   │       └─┬ @babel/highlight@7.0.0-beta.51
│   │         └─┬ chalk@2.4.1 
│   │           ├─┬ ansi-styles@3.2.1 
│   │           │ └── color-convert@1.9.3 
│   │           └─┬ supports-color@5.5.0 
│   │             └── has-flag@3.0.0 
│   ├─┬ jest-config@20.0.4
│   │ └─┬ pretty-format@20.0.3
│   │   └─┬ ansi-styles@3.2.1 
│   │     └── color-convert@1.9.3 
│   └─┬ jest-environment-jsdom@20.0.3
│     └─┬ jsdom@9.12.0
│       └─┬ escodegen@1.11.0
│         └── source-map@0.6.1 
├─┬ postcss-cssnext@2.11.0
│ ├─┬ postcss-color-gray@3.0.1
│ │ └─┬ color@0.11.4
│ │   └── color-convert@1.9.3 
│ └─┬ postcss-image-set-polyfill@0.3.5
│   └─┬ postcss@6.0.23 
│     ├─┬ chalk@2.4.1 
│     │ └─┬ ansi-styles@3.2.1 
│     │   └── color-convert@1.9.3 
│     ├── source-map@0.6.1 
│     └─┬ supports-color@5.5.0 
│       └── has-flag@3.0.0 
├─┬ postcss-mixins@6.2.0
│ ├─┬ postcss@6.0.23 
│ │ ├─┬ chalk@2.4.1 
│ │ │ └─┬ ansi-styles@3.2.1 
│ │ │   └── color-convert@1.9.3 
│ │ ├── source-map@0.6.1 
│ │ └─┬ supports-color@5.5.0 
│ │   └── has-flag@3.0.0 
│ ├─┬ postcss-js@1.0.1
│ │ └─┬ postcss@6.0.23 
│ │   ├─┬ chalk@2.4.1 
│ │   │ └─┬ ansi-styles@3.2.1 
│ │   │   └── color-convert@1.9.3 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@5.5.0 
│ │     └── has-flag@3.0.0 
│ ├─┬ postcss-simple-vars@4.1.0
│ │ └─┬ postcss@6.0.23 
│ │   ├─┬ chalk@2.4.1 
│ │   │ └─┬ ansi-styles@3.2.1 
│ │   │   └── color-convert@1.9.3 
│ │   ├── source-map@0.6.1 
│ │   └─┬ supports-color@5.5.0 
│ │     └── has-flag@3.0.0 
│ └─┬ sugarss@1.0.1
│   └─┬ postcss@6.0.23 
│     ├─┬ chalk@2.4.1 
│     │ └─┬ ansi-styles@3.2.1 
│     │   └── color-convert@1.9.3 
│     ├── source-map@0.6.1 
│     └─┬ supports-color@5.5.0 
│       └── has-flag@3.0.0 
└─┬ webpack-dev-server@2.11.3
  └─┬ supports-color@5.5.0 
    └── has-flag@3.0.0 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

**Comment by billchurch** [comment]
@ankitAMD what version of node are you running, this is only supported on Node v6 and above.

**Comment by billchurch** [comment]
@ankitAMD also please use "npm install --production" unless you plan on doing some development. If your plan on doing development you'll need developer tools like a complier, linker, etc... and instructions for how to set that up are beyond the scope of this project.

**Comment by rowanD72** [comment]
> Same for me.. Just switched to ubuntu 18 and get this, when trying to install Bootstrap 4
> 
> ```
> 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
> ```

If you have yarn installed, just download Bootstrap from there. It worked for me. If you don't have yarn downloaded go to yarnpkg.com

**Comment by ankitAMD** [comment]
okk thank you for replying

**Comment by Drug0j** [comment]
Hi ubuntu 16.04
npm WARN optional Skipping failed optional dependency /webpack/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4


plese install help!

**Comment by billchurch** [comment]
Use:

`npm install --production` instead

What OS, version of node,  version of npm, and post full log and output here.

**Comment by Miko2x** [comment]
- What OS ?
_Ubuntu 18.04.1 LTS_
- Version of Node ?
_v8.10.0_
- Version of NPM ?
_3.5.2_

## Here the output after using `npm install --production` command:
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /jest/sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /jest-runner/sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /jest-runtime/sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4

**Comment by billchurch** [comment]
@miko2x what CPU architecutre is this? ARM or something else?

**Comment by ssvk123** [comment]
i am also dealing with same problem..

**Comment by NanoBjorn** [comment]
same here, `npm install --production` didn't help

**Comment by mmomtchev** [comment]
You can safely ignore this message, it has been popping in lots of projects lately.
The chokidar module has an optional dependency on fsevents which works only on OS X.
All projects depending on chokidar will display this warning message when updating node_modules on a non OS X target.

**Comment by wcypierre** [comment]
For the fsevents, I'm seeing it on other libraries as well. If you're not using OS X, you can add --no-optional during npm install to exclude out fsevents instead (i.e npm install --no-optional)

**Comment by nikhilkanamadi** [comment]
When i'm using **nodemon** command, i'm getting this error: 
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7

Is it Hardware/ OS Architecture Dependent? :/

**Comment by ForTimeBeing** [comment]
I get the same error running `npm install --production` and running the argument --no-optional for npm DID remove the errors, although when I try to run webpack it still says webpack is not installed

**Comment by jenishlila** [comment]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.1.3
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN optional Skipping failed optional dependency /watchify/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN httpdocs No repository field.
npm WARN httpdocs No license field.

i am having this issue
how can i solve this?
