### ISSUE TITLE
having trouble configuring for localhost

### ISSUE THREAD

**Issue by rharker** [billchurch/WebSSH2#91]
All I want to do is give my users access to the local host TTY so they can execute a reservation script from the web.  Not sure on how to configure WebSSH2
My system is configured to use port 32611 for SSH and port 22 is closed

Node Version v10.8.0
Server OS Version Centos 7
WebSSH2 release version latest
OS and Version of SSH server connecting to
Browser Version and OS??

**Comment by billchurch** [comment]
You need a url with something like:

`http://<youripaddress>:<port WebSSH2 listening on>/ssh/host/localhost?port=32611`
