### ISSUE TITLE
SSH CONN ERROR: All configured authentication methods failed

### ISSUE THREAD

**Issue by ahaii** [billchurch/WebSSH2#92]
Node  v8.11.3
CentOS 7.2 64bit
webssh2@0.2.3
Chrome  68.0.3440.106 &&  Safari 11.1.2 (11605.3.8.1) for MacOS(10.11.6)
 
When SSH another Server in same browser , occurred this error.
Can you tell me what can i do?
Thank you so much!

**Comment by billchurch** [comment]
See solution in issue #51
