### ISSUE TITLE
Cannot use the webSSH2 when the browser and the webSSH2 not on a same machine

### ISSUE THREAD

**Issue by arscoke** [billchurch/WebSSH2#93]
Now I put the webssh2 project and run it on an centos7, for example the ip is: 192.168.0.1.
Then I back to my own windows machine which ip maybe 192.168.0.3, and in the browser, I call the url like: http://192.168.0.1/ssh/host/192.168.0.2

it cannot connect. Only error in the browser is :  ERR_CONNECTION_REFUSED
Can you give me some help? Very thanks, I wait your response...   :)

**Comment by billchurch** [comment]
@arscoke, i need a bit more detail here. There's no reason this shouldn't work, but it sounds like you might be missing the port in your URL. Usually it's :2222

`http://192.168.0.1:2222/ssh/host/192.168.0.2`

If you're trying to listen to port 80, you'll need to run the node process as root and change the port in `config.json` to port 80... I WOULD NOT recommend running this as root, and instead use some sort of reverse proxy, something like nginx or the like. Example for nginx here https://medium.com/@utkarsh_verma/configure-nginx-as-a-web-server-and-reverse-proxy-for-nodejs-application-on-aws-ubuntu-16-04-server-872922e21d38 note the nodejs port is 8080 for this example.
