### ISSUE TITLE
Run command when browser successfully connect to SSH

### ISSUE THREAD

**Issue by levon1998** [billchurch/WebSSH2#94]
Hello everyone, 
I want to connect to remote server by ssh when browser terminal will successfully connected

**Comment by billchurch** [comment]
Right now the app will invoke `shell` vs `exec`

If you look at this line:
https://github.com/billchurch/WebSSH2/blob/05934e8b19575d7b39cf882a16978aabb9edd8ad/server/socket.js#L45

Switching it to something like will run /usr/bin/top:
```
    conn.exec('/usr/bin/top', {
      term: socket.request.session.ssh.term,
      cols: termCols,
      rows: termRows
    }, function connShell (err, stream) {
```

**Comment by levon1998** [comment]
@billchurch thank you so much for fast answer i have already find my solution. i am using "stream.write('command \n')" i all work perfectly ))

**Comment by billchurch** [comment]
Oh yeah, that would work too... Just depends on what you're trying to accomplish.

Just keep in mind, with your approach if a user terminates that process it will return a shell... As long as that's what you want.
