### ISSUE TITLE
How to have socket server on different server to the client? 

### ISSUE THREAD

**Issue by Banegasn** [billchurch/WebSSH2#97]
I have a running website in php that i like to add a web console feature,
i figure that i can put WebSSH2/client/public files in my apache server 
and connect to a nodejs in other host with the socket server

but it keeps saying `invalid namespace` when i try to connect 
anyone have tried this?

**Comment by billchurch** [comment]
really need to look into using a reverse proxy and proxy pass. Kind of out of scope for this project.

see this for an example:
https://serverfault.com/questions/429404/help-me-understand-how-to-use-proxypass
